// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// AcceleratorConfig represents a Hardware Accelerator request.
public struct AcceleratorConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The number of the accelerator cards exposed to an instance.
  public var acceleratorCount: Swift.Int64 = Swift.Int64()

  /// The accelerator type resource name. List of supported accelerators
  /// [here](https://cloud.google.com/compute/docs/gpus)
  public var acceleratorType: Swift.String = Swift.String()

  /// Size of partitions to create on the GPU. Valid values are described in the
  /// NVIDIA [mig user
  /// guide](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#partitioning).
  public var gpuPartitionSize: Swift.String = Swift.String()

  /// The configuration for GPU sharing options.
  public var gpuSharingConfig: GPUSharingConfig? = nil

  /// The configuration for auto installation of GPU driver.
  public var gpuDriverInstallationConfig: GPUDriverInstallationConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AcceleratorConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AcceleratorConfig().with { $0.acceleratorCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let acceleratorCount = CodingKeys(stringValue: "acceleratorCount")
    static let acceleratorType = CodingKeys(stringValue: "acceleratorType")
    static let gpuPartitionSize = CodingKeys(stringValue: "gpuPartitionSize")
    static let gpuSharingConfig = CodingKeys(stringValue: "gpuSharingConfig")
    static let gpuDriverInstallationConfig = CodingKeys(stringValue: "gpuDriverInstallationConfig")

    static let _knownKeys: Set<Swift.String> = [
      "acceleratorCount",
      "acceleratorType",
      "gpuPartitionSize",
      "gpuSharingConfig",
      "gpuDriverInstallationConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .acceleratorCount) {
      self.acceleratorCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .acceleratorType) {
      self.acceleratorType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gpuPartitionSize) {
      self.gpuPartitionSize = value
    }
    self.gpuSharingConfig = try container.decodeIfPresent(
      GPUSharingConfig.self, forKey: .gpuSharingConfig)
    self.gpuDriverInstallationConfig = try container.decodeIfPresent(
      GPUDriverInstallationConfig.self, forKey: .gpuDriverInstallationConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.acceleratorCount, forKey: .acceleratorCount)
    try container.encode(self.acceleratorType, forKey: .acceleratorType)
    try container.encode(self.gpuPartitionSize, forKey: .gpuPartitionSize)
    try container.encodeIfPresent(self.gpuSharingConfig, forKey: .gpuSharingConfig)
    try container.encodeIfPresent(
      self.gpuDriverInstallationConfig, forKey: .gpuDriverInstallationConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.AcceleratorConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
