// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// AdditionalPodNetworkConfig is the configuration for additional pod networks
/// within the NodeNetworkConfig message
public struct AdditionalPodNetworkConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Name of the subnetwork where the additional pod network belongs.
  public var subnetwork: Swift.String = Swift.String()

  /// The name of the secondary range on the subnet which provides IP address for
  /// this pod range.
  public var secondaryPodRange: Swift.String = Swift.String()

  /// The maximum number of pods per node which use this pod network.
  public var maxPodsPerNode: MaxPodsConstraint? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AdditionalPodNetworkConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdditionalPodNetworkConfig().with { $0.subnetwork = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let subnetwork = CodingKeys(stringValue: "subnetwork")
    static let secondaryPodRange = CodingKeys(stringValue: "secondaryPodRange")
    static let maxPodsPerNode = CodingKeys(stringValue: "maxPodsPerNode")

    static let _knownKeys: Set<Swift.String> = [
      "subnetwork",
      "secondaryPodRange",
      "maxPodsPerNode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork) {
      self.subnetwork = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryPodRange) {
      self.secondaryPodRange = value
    }
    self.maxPodsPerNode = try container.decodeIfPresent(
      MaxPodsConstraint.self, forKey: .maxPodsPerNode)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.subnetwork, forKey: .subnetwork)
    try container.encode(self.secondaryPodRange, forKey: .secondaryPodRange)
    try container.encodeIfPresent(self.maxPodsPerNode, forKey: .maxPodsPerNode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.AdditionalPodNetworkConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
