// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AdvancedDatapathObservabilityConfig specifies configuration of observability
/// features of advanced datapath.
public struct AdvancedDatapathObservabilityConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Expose flow metrics on nodes
  public var enableMetrics: Swift.Bool = Swift.Bool()

  /// Method used to make Relay available
  public var relayMode: AdvancedDatapathObservabilityConfig.RelayMode =
    AdvancedDatapathObservabilityConfig.RelayMode()

  /// Enable Relay component
  public var enableRelay: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AdvancedDatapathObservabilityConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdvancedDatapathObservabilityConfig().with { $0.enableMetrics = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enableMetrics = CodingKeys(stringValue: "enableMetrics")
    static let relayMode = CodingKeys(stringValue: "relayMode")
    static let enableRelay = CodingKeys(stringValue: "enableRelay")

    static let _knownKeys: Set<Swift.String> = [
      "enableMetrics",
      "relayMode",
      "enableRelay",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableMetrics) {
      self.enableMetrics = value
    }
    if let value = try container.decodeIfPresent(
      AdvancedDatapathObservabilityConfig.RelayMode.self, forKey: .relayMode)
    {
      self.relayMode = value
    }
    self.enableRelay = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableRelay)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enableMetrics, forKey: .enableMetrics)
    try container.encode(self.relayMode, forKey: .relayMode)
    try container.encodeIfPresent(self.enableRelay, forKey: .enableRelay)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Supported Relay modes
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum RelayMode: Codable, Equatable, Sendable {
    /// Default value. This shouldn't be used.
    case unspecified
    /// disabled
    case disabled
    /// exposed via internal load balancer
    case internalVpcLb
    /// exposed via external load balancer
    case externalLb
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .disabled: return 1
      case .internalVpcLb: return 3
      case .externalLb: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RELAY_MODE_UNSPECIFIED"
      case .disabled: return "DISABLED"
      case .internalVpcLb: return "INTERNAL_VPC_LB"
      case .externalLb: return "EXTERNAL_LB"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RelayMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RELAY_MODE_UNSPECIFIED": self = .unspecified
      case "DISABLED": self = .disabled
      case "INTERNAL_VPC_LB": self = .internalVpcLb
      case "EXTERNAL_LB": self = .externalLb
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RelayMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .disabled
      case 3: self = .internalVpcLb
      case 4: self = .externalLb
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RELAY_MODE_UNSPECIFIED")
      case .disabled: return try container.encode("DISABLED")
      case .internalVpcLb: return try container.encode("INTERNAL_VPC_LB")
      case .externalLb: return try container.encode("EXTERNAL_LB")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.AdvancedDatapathObservabilityConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
