// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies options for controlling advanced machine features.
public struct AdvancedMachineFeatures: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The number of threads per physical core. To disable simultaneous
  /// multithreading (SMT) set this to 1. If unset, the maximum number of threads
  /// supported per core by the underlying processor is assumed.
  public var threadsPerCore: Swift.Int64? = nil

  /// Whether or not to enable nested virtualization (defaults to false).
  public var enableNestedVirtualization: Swift.Bool? = nil

  /// Type of Performance Monitoring Unit (PMU) requested on node pool instances.
  /// If unset, PMU will not be available to the node.
  public var performanceMonitoringUnit: AdvancedMachineFeatures.PerformanceMonitoringUnit? = nil

  /// Initialize a new instance of `AdvancedMachineFeatures`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdvancedMachineFeatures().with { $0.threadsPerCore = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Level of PMU access.
  public enum PerformanceMonitoringUnit: Codable, Equatable, Sendable {
    /// PMU not enabled.
    case unspecified
    /// Architecturally defined non-LLC events.
    case architectural
    /// Most documented core/L2 events.
    case standard
    /// Most documented core/L2 and LLC events.
    case enhanced
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .architectural: return 1
      case .standard: return 2
      case .enhanced: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PERFORMANCE_MONITORING_UNIT_UNSPECIFIED"
      case .architectural: return "ARCHITECTURAL"
      case .standard: return "STANDARD"
      case .enhanced: return "ENHANCED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PerformanceMonitoringUnit/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PERFORMANCE_MONITORING_UNIT_UNSPECIFIED": self = .unspecified
      case "ARCHITECTURAL": self = .architectural
      case "STANDARD": self = .standard
      case "ENHANCED": self = .enhanced
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PerformanceMonitoringUnit/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .architectural
      case 2: self = .standard
      case 3: self = .enhanced
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .architectural: return try container.encode(1)
      case .standard: return try container.encode(2)
      case .enhanced: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.AdvancedMachineFeatures"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
