// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AutoprovisioningNodePoolDefaults contains defaults for a node pool created
/// by NAP.
public struct AutoprovisioningNodePoolDefaults: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Scopes that are used by NAP when creating node pools.
  public var oauthScopes: [Swift.String] = []

  /// The Google Cloud Platform Service Account to be used by the node VMs.
  public var serviceAccount: Swift.String = Swift.String()

  /// Specifies the upgrade settings for NAP created node pools
  public var upgradeSettings: NodePool.UpgradeSettings? = nil

  /// Specifies the node management options for NAP created node-pools.
  public var management: NodeManagement? = nil

  /// Deprecated. Minimum CPU platform to be used for NAP created node pools.
  /// The instance may be scheduled on the specified or newer CPU platform.
  /// Applicable values are the friendly names of CPU platforms, such as
  /// minCpuPlatform: Intel Haswell or
  /// minCpuPlatform: Intel Sandy Bridge. For more
  /// information, read [how to specify min CPU
  /// platform](https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform).
  /// This field is deprecated, min_cpu_platform should be specified using
  /// `cloud.google.com/requested-min-cpu-platform` label selector on the pod.
  /// To unset the min cpu platform field pass "automatic"
  /// as field value.
  @available(*, deprecated)
  public var minCpuPlatform: Swift.String = Swift.String()

  /// Size of the disk attached to each node, specified in GB.
  /// The smallest allowed disk size is 10GB.
  ///
  /// If unspecified, the default disk size is 100GB.
  public var diskSizeGb: Swift.Int32 = Swift.Int32()

  /// Type of the disk attached to each node (e.g. 'pd-standard', 'pd-ssd' or
  /// 'pd-balanced')
  ///
  /// If unspecified, the default disk type is 'pd-standard'
  public var diskType: Swift.String = Swift.String()

  /// Shielded Instance options.
  public var shieldedInstanceConfig: ShieldedInstanceConfig? = nil

  /// The Customer Managed Encryption Key used to encrypt the boot disk attached
  /// to each node in the node pool. This should be of the form
  /// projects/[KEY_PROJECT_ID]/locations/[LOCATION]/keyRings/[RING_NAME]/cryptoKeys/[KEY_NAME].
  /// For more information about protecting resources with Cloud KMS Keys please
  /// see:
  /// https://cloud.google.com/compute/docs/disks/customer-managed-encryption
  public var bootDiskKmsKey: Swift.String = Swift.String()

  /// The image type to use for NAP created node. Please see
  /// https://cloud.google.com/kubernetes-engine/docs/concepts/node-images
  /// for available image types.
  public var imageType: Swift.String = Swift.String()

  /// DEPRECATED. Use NodePoolAutoConfig.NodeKubeletConfig instead.
  public var insecureKubeletReadonlyPortEnabled: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AutoprovisioningNodePoolDefaults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutoprovisioningNodePoolDefaults().with { $0.oauthScopes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let oauthScopes = CodingKeys(stringValue: "oauthScopes")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let upgradeSettings = CodingKeys(stringValue: "upgradeSettings")
    static let management = CodingKeys(stringValue: "management")
    static let minCpuPlatform = CodingKeys(stringValue: "minCpuPlatform")
    static let diskSizeGb = CodingKeys(stringValue: "diskSizeGb")
    static let diskType = CodingKeys(stringValue: "diskType")
    static let shieldedInstanceConfig = CodingKeys(stringValue: "shieldedInstanceConfig")
    static let bootDiskKmsKey = CodingKeys(stringValue: "bootDiskKmsKey")
    static let imageType = CodingKeys(stringValue: "imageType")
    static let insecureKubeletReadonlyPortEnabled = CodingKeys(
      stringValue: "insecureKubeletReadonlyPortEnabled")

    static let _knownKeys: Set<Swift.String> = [
      "oauthScopes",
      "serviceAccount",
      "upgradeSettings",
      "management",
      "minCpuPlatform",
      "diskSizeGb",
      "diskType",
      "shieldedInstanceConfig",
      "bootDiskKmsKey",
      "imageType",
      "insecureKubeletReadonlyPortEnabled",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .oauthScopes) {
      self.oauthScopes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    self.upgradeSettings = try container.decodeIfPresent(
      NodePool.UpgradeSettings.self, forKey: .upgradeSettings)
    self.management = try container.decodeIfPresent(NodeManagement.self, forKey: .management)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .minCpuPlatform) {
      self.minCpuPlatform = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .diskSizeGb) {
      self.diskSizeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .diskType) {
      self.diskType = value
    }
    self.shieldedInstanceConfig = try container.decodeIfPresent(
      ShieldedInstanceConfig.self, forKey: .shieldedInstanceConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .bootDiskKmsKey) {
      self.bootDiskKmsKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageType) {
      self.imageType = value
    }
    self.insecureKubeletReadonlyPortEnabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .insecureKubeletReadonlyPortEnabled)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.oauthScopes, forKey: .oauthScopes)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encodeIfPresent(self.upgradeSettings, forKey: .upgradeSettings)
    try container.encodeIfPresent(self.management, forKey: .management)
    try container.encode(self.minCpuPlatform, forKey: .minCpuPlatform)
    try container.encode(self.diskSizeGb, forKey: .diskSizeGb)
    try container.encode(self.diskType, forKey: .diskType)
    try container.encodeIfPresent(self.shieldedInstanceConfig, forKey: .shieldedInstanceConfig)
    try container.encode(self.bootDiskKmsKey, forKey: .bootDiskKmsKey)
    try container.encode(self.imageType, forKey: .imageType)
    try container.encodeIfPresent(
      self.insecureKubeletReadonlyPortEnabled, forKey: .insecureKubeletReadonlyPortEnabled)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.AutoprovisioningNodePoolDefaults"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
