// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// BootDisk specifies the boot disk configuration for node pools.
public struct BootDisk: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Disk type of the boot disk.
  /// (i.e. Hyperdisk-Balanced, PD-Balanced, etc.)
  public var diskType: Swift.String = Swift.String()

  /// Disk size in GB. Replaces NodeConfig.disk_size_gb
  public var sizeGb: Swift.Int64 = Swift.Int64()

  /// For Hyperdisk-Balanced only, the provisioned IOPS config value.
  public var provisionedIops: Swift.Int64 = Swift.Int64()

  /// For Hyperdisk-Balanced only, the provisioned throughput config value.
  public var provisionedThroughput: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `BootDisk`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BootDisk().with { $0.diskType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.BootDisk"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
