// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// ClusterPolicyConfig stores the configuration for cluster wide policies.
public struct ClusterPolicyConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Denotes that preventing creation and mutation of resources in GKE
  /// managed namespaces and cluster-scoped GKE managed resources .
  public var noSystemMutation: Swift.Bool? = nil

  /// Denotes preventing impersonation and CSRs for GKE System users.
  public var noSystemImpersonation: Swift.Bool? = nil

  /// Denotes preventing unsafe webhooks.
  public var noUnsafeWebhooks: Swift.Bool? = nil

  /// Denotes preventing standard node pools and requiring only autopilot node
  /// pools.
  public var noStandardNodePools: Swift.Bool? = nil

  /// Initialize a new instance of `ClusterPolicyConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClusterPolicyConfig().with { $0.noSystemMutation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.ClusterPolicyConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
