// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol ClusterManagerStub: Sendable {
    func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.ListClustersResponse

    func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Cluster

    func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func updateCluster(
      request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func updateNodePool(
      request: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setNodePoolAutoscaling(
      request: SetNodePoolAutoscalingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setLoggingService(
      request: SetLoggingServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setMonitoringService(
      request: SetMonitoringServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setAddonsConfig(
      request: SetAddonsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setLocations(
      request: SetLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func updateMaster(
      request: UpdateMasterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setMasterAuth(
      request: SetMasterAuthRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.ListOperationsResponse

    func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func cancelOperation(
      request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getServerConfig(
      request: GetServerConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.ServerConfig

    func getJsonwebKeys(
      request: GetJSONWebKeysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.GetJSONWebKeysResponse

    func listNodePools(
      request: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.ListNodePoolsResponse

    func getNodePool(
      request: GetNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.NodePool

    func createNodePool(
      request: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func deleteNodePool(
      request: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func completeNodePoolUpgrade(
      request: CompleteNodePoolUpgradeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func rollbackNodePoolUpgrade(
      request: RollbackNodePoolUpgradeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setNodePoolManagement(
      request: SetNodePoolManagementRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setLabels(
      request: SetLabelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setLegacyAbac(
      request: SetLegacyAbacRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func startIprotation(
      request: StartIPRotationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func completeIprotation(
      request: CompleteIPRotationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setNodePoolSize(
      request: SetNodePoolSizeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setNetworkPolicy(
      request: SetNetworkPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func setMaintenancePolicy(
      request: SetMaintenancePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.Operation

    func listUsableSubnetworks(
      request: ListUsableSubnetworksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.ListUsableSubnetworksResponse

    func checkAutopilotCompatibility(
      request: CheckAutopilotCompatibilityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.CheckAutopilotCompatibilityResponse

    func fetchClusterUpgradeInfo(
      request: FetchClusterUpgradeInfoRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.ClusterUpgradeInfo

    func fetchNodePoolUpgradeInfo(
      request: FetchNodePoolUpgradeInfoRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerV1.NodePoolUpgradeInfo
  }
}
