// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration for all of the cluster's control plane endpoints.
public struct ControlPlaneEndpointsConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// DNS endpoint configuration.
  public var dnsEndpointConfig: ControlPlaneEndpointsConfig.DNSEndpointConfig? = nil

  /// IP endpoints configuration.
  public var ipEndpointsConfig: ControlPlaneEndpointsConfig.IPEndpointsConfig? = nil

  /// Initialize a new instance of `ControlPlaneEndpointsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ControlPlaneEndpointsConfig().with { $0.dnsEndpointConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Describes the configuration of a DNS endpoint.
  public struct DNSEndpointConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The cluster's DNS endpoint configuration.
    /// A DNS format address. This is accessible from the public internet.
    /// Ex: uid.us-central1.gke.goog.
    /// Always present, but the behavior may change according to the value of
    /// [DNSEndpointConfig.allow_external_traffic][google.container.v1.ControlPlaneEndpointsConfig.DNSEndpointConfig.allow_external_traffic].
    ///
    /// [google.container.v1.ControlPlaneEndpointsConfig.DNSEndpointConfig.allow_external_traffic]: <doc:ControlPlaneEndpointsConfig/DNSEndpointConfig/allowExternalTraffic>
    public var endpoint: Swift.String = Swift.String()

    /// Controls whether user traffic is allowed over this endpoint. Note that
    /// Google-managed services may still use the endpoint even if this is false.
    public var allowExternalTraffic: Swift.Bool? = nil

    /// Controls whether the k8s token auth is allowed via DNS.
    public var enableK8STokensViaDns: Swift.Bool? = nil

    /// Controls whether the k8s certs auth is allowed via DNS.
    public var enableK8SCertsViaDns: Swift.Bool? = nil

    /// Initialize a new instance of `DNSEndpointConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DNSEndpointConfig().with { $0.endpoint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case endpoint = "endpoint"
      case allowExternalTraffic = "allowExternalTraffic"
      case enableK8STokensViaDns = "enableK8sTokensViaDns"
      case enableK8SCertsViaDns = "enableK8sCertsViaDns"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.endpoint = try container.decode(Swift.String.self, forKey: .endpoint)
      self.allowExternalTraffic = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .allowExternalTraffic)
      self.enableK8STokensViaDns = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .enableK8STokensViaDns)
      self.enableK8SCertsViaDns = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .enableK8SCertsViaDns)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.endpoint, forKey: .endpoint)
      try container.encode(self.allowExternalTraffic, forKey: .allowExternalTraffic)
      try container.encode(self.enableK8STokensViaDns, forKey: .enableK8STokensViaDns)
      try container.encode(self.enableK8SCertsViaDns, forKey: .enableK8SCertsViaDns)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.container.v1.ControlPlaneEndpointsConfig.DNSEndpointConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// IP endpoints configuration.
  public struct IPEndpointsConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Controls whether to allow direct IP access.
    public var enabled: Swift.Bool? = nil

    /// Controls whether the control plane allows access through a public IP.
    /// It is invalid to specify both
    /// [PrivateClusterConfig.enablePrivateEndpoint][] and this field at the same
    /// time.
    public var enablePublicEndpoint: Swift.Bool? = nil

    /// Controls whether the control plane's private endpoint is accessible from
    /// sources in other regions.
    /// It is invalid to specify both
    /// [PrivateClusterMasterGlobalAccessConfig.enabled][google.container.v1.PrivateClusterMasterGlobalAccessConfig.enabled]
    /// and this field at the same time.
    ///
    /// [google.container.v1.PrivateClusterMasterGlobalAccessConfig.enabled]: <doc:PrivateClusterMasterGlobalAccessConfig/enabled>
    public var globalAccess: Swift.Bool? = nil

    /// Configuration of authorized networks. If enabled, restricts access to the
    /// control plane based on source IP.
    /// It is invalid to specify both
    /// [Cluster.masterAuthorizedNetworksConfig][] and this field at the same
    /// time.
    public var authorizedNetworksConfig: MasterAuthorizedNetworksConfig? = nil

    /// Output only. The external IP address of this cluster's control plane.
    /// Only populated if enabled.
    public var publicEndpoint: Swift.String = Swift.String()

    /// Output only. The internal IP address of this cluster's control plane.
    /// Only populated if enabled.
    public var privateEndpoint: Swift.String = Swift.String()

    /// Subnet to provision the master's private endpoint during cluster
    /// creation. Specified in projects/*/regions/*/subnetworks/* format. It is
    /// invalid to specify both
    /// [PrivateClusterConfig.privateEndpointSubnetwork][] and this field at the
    /// same time.
    public var privateEndpointSubnetwork: Swift.String = Swift.String()

    /// Initialize a new instance of `IPEndpointsConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IPEndpointsConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.container.v1.ControlPlaneEndpointsConfig.IPEndpointsConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.ControlPlaneEndpointsConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
