// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DisruptionEvent is a notification sent to customers about the disruption
/// event of a resource.
public struct DisruptionEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The type of the disruption event.
  public var disruptionType: DisruptionEvent.DisruptionType = DisruptionEvent.DisruptionType()

  /// The node whose drain is blocked by PDB. This field is set for both
  /// POD_PDB_VIOLATION and POD_NOT_ENOUGH_PDB event.
  public var pdbBlockedNode: Swift.String = Swift.String()

  /// The pods whose evictions are blocked by PDB. This field is set for
  /// both POD_PDB_VIOLATION and POD_NOT_ENOUGH_PDB event.
  public var pdbBlockedPod: [DisruptionEvent.PdbBlockedPod] = []

  /// The timeout in seconds for which the node drain is blocked by PDB.
  /// After this timeout, pods are forcefully evicted.
  /// This field is only populated when event_type is
  /// POD_PDB_VIOLATION.
  public var pdbViolationTimeout: GoogleWKT.WKTDuration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DisruptionEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DisruptionEvent().with { $0.disruptionType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let disruptionType = CodingKeys(stringValue: "disruptionType")
    static let pdbBlockedNode = CodingKeys(stringValue: "pdbBlockedNode")
    static let pdbBlockedPod = CodingKeys(stringValue: "pdbBlockedPod")
    static let pdbViolationTimeout = CodingKeys(stringValue: "pdbViolationTimeout")

    static let _knownKeys: Set<Swift.String> = [
      "disruptionType",
      "pdbBlockedNode",
      "pdbBlockedPod",
      "pdbViolationTimeout",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      DisruptionEvent.DisruptionType.self, forKey: .disruptionType)
    {
      self.disruptionType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pdbBlockedNode) {
      self.pdbBlockedNode = value
    }
    if let value = try container.decodeIfPresent(
      [DisruptionEvent.PdbBlockedPod].self, forKey: .pdbBlockedPod)
    {
      self.pdbBlockedPod = value
    }
    self.pdbViolationTimeout = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .pdbViolationTimeout)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.disruptionType, forKey: .disruptionType)
    try container.encode(self.pdbBlockedNode, forKey: .pdbBlockedNode)
    try container.encode(self.pdbBlockedPod, forKey: .pdbBlockedPod)
    try container.encodeIfPresent(self.pdbViolationTimeout, forKey: .pdbViolationTimeout)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The namespace/name of the pod whose eviction is blocked by PDB.
  public struct PdbBlockedPod: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The namespace of the pod.
    public var namespace: Swift.String = Swift.String()

    /// The name of the pod.
    public var name: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PdbBlockedPod`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PdbBlockedPod().with { $0.namespace = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let namespace = CodingKeys(stringValue: "namespace")
      static let name = CodingKeys(stringValue: "name")

      static let _knownKeys: Set<Swift.String> = [
        "namespace",
        "name",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .namespace) {
        self.namespace = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.namespace, forKey: .namespace)
      try container.encode(self.name, forKey: .name)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.container.v1.DisruptionEvent.PdbBlockedPod"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of the disruption event.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DisruptionType: Codable, Equatable, Sendable {
    /// DISRUPTION_TYPE_UNSPECIFIED indicates the disruption type is unspecified.
    case unspecified
    /// POD_NOT_ENOUGH_PDB indicates there are still running pods
    /// on the node during node drain because their evictions are blocked by PDB.
    case podNotEnoughPdb
    /// POD_PDB_VIOLATION indicates that there are force pod
    /// evictions during node drain which violate the PDB.
    case podPdbViolation
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .podNotEnoughPdb: return 1
      case .podPdbViolation: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISRUPTION_TYPE_UNSPECIFIED"
      case .podNotEnoughPdb: return "POD_NOT_ENOUGH_PDB"
      case .podPdbViolation: return "POD_PDB_VIOLATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DisruptionType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISRUPTION_TYPE_UNSPECIFIED": self = .unspecified
      case "POD_NOT_ENOUGH_PDB": self = .podNotEnoughPdb
      case "POD_PDB_VIOLATION": self = .podPdbViolation
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DisruptionType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .podNotEnoughPdb
      case 2: self = .podPdbViolation
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISRUPTION_TYPE_UNSPECIFIED")
      case .podNotEnoughPdb: return try container.encode("POD_NOT_ENOUGH_PDB")
      case .podPdbViolation: return try container.encode("POD_PDB_VIOLATION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.DisruptionEvent"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
