// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Node kubelet configs.
public struct NodeKubeletConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Control the CPU management policy on the node.
  /// See
  /// https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/
  ///
  /// The following values are allowed.
  /// * "none": the default, which represents the existing scheduling behavior.
  /// * "static": allows pods with certain resource characteristics to be granted
  /// increased CPU affinity and exclusivity on the node.
  /// The default value is 'none' if unspecified.
  public var cpuManagerPolicy: Swift.String = Swift.String()

  /// Optional. Controls Topology Manager configuration on the node.
  /// For more information, see:
  /// https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/
  public var topologyManager: TopologyManager? = nil

  /// Optional. Controls NUMA-aware Memory Manager configuration on the
  /// node. For more information, see:
  /// https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/
  public var memoryManager: MemoryManager? = nil

  /// Enable CPU CFS quota enforcement for containers that specify CPU limits.
  ///
  /// This option is enabled by default which makes kubelet use CFS quota
  /// (https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt) to
  /// enforce container CPU limits. Otherwise, CPU limits will not be enforced at
  /// all.
  ///
  /// Disable this option to mitigate CPU throttling problems while still having
  /// your pods to be in Guaranteed QoS class by specifying the CPU limits.
  ///
  /// The default value is 'true' if unspecified.
  public var cpuCfsQuota: GoogleCloudWKT.BoolValue? = nil

  /// Set the CPU CFS quota period value 'cpu.cfs_period_us'.
  ///
  /// The string must be a sequence of decimal numbers, each with optional
  /// fraction and a unit suffix, such as "300ms".
  /// Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  /// The value must be a positive duration between 1ms and 1 second, inclusive.
  public var cpuCfsQuotaPeriod: Swift.String = Swift.String()

  /// Set the Pod PID limits. See
  /// https://kubernetes.io/docs/concepts/policy/pid-limiting/#pod-pid-limits
  ///
  /// Controls the maximum number of processes allowed to run in a pod. The value
  /// must be greater than or equal to 1024 and less than 4194304.
  public var podPidsLimit: Swift.Int64 = Swift.Int64()

  /// Enable or disable Kubelet read only port.
  public var insecureKubeletReadonlyPortEnabled: Swift.Bool? = nil

  /// Optional. Defines the percent of disk usage before which image garbage
  /// collection is never run. Lowest disk usage to garbage collect to. The
  /// percent is calculated as this field value out of 100.
  ///
  /// The value must be between 10 and 85, inclusive and smaller than
  /// image_gc_high_threshold_percent.
  ///
  /// The default value is 80 if unspecified.
  public var imageGcLowThresholdPercent: Swift.Int32 = Swift.Int32()

  /// Optional. Defines the percent of disk usage after which image garbage
  /// collection is always run. The percent is calculated as this field value out
  /// of 100.
  ///
  /// The value must be between 10 and 85, inclusive and greater than
  /// image_gc_low_threshold_percent.
  ///
  /// The default value is 85 if unspecified.
  public var imageGcHighThresholdPercent: Swift.Int32 = Swift.Int32()

  /// Optional. Defines the minimum age for an unused image before it is garbage
  /// collected.
  ///
  /// The string must be a sequence of decimal numbers, each with optional
  /// fraction and a unit suffix, such as "300s", "1.5h", and "2h45m". Valid time
  /// units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  ///
  /// The value must be a positive duration less than or equal to 2 minutes.
  ///
  /// The default value is "2m0s" if unspecified.
  public var imageMinimumGcAge: Swift.String = Swift.String()

  /// Optional. Defines the maximum age an image can be unused before it is
  /// garbage collected. The string must be a sequence of decimal numbers, each
  /// with optional fraction and a unit suffix, such as "300s", "1.5h", and
  /// "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  ///
  /// The value must be a positive duration greater than image_minimum_gc_age
  /// or "0s".
  ///
  /// The default value is "0s" if unspecified, which disables this field,
  /// meaning images won't be garbage collected based on being unused for too
  /// long.
  public var imageMaximumGcAge: Swift.String = Swift.String()

  /// Optional. Defines the maximum size of the container log file before it is
  /// rotated. See
  /// https://kubernetes.io/docs/concepts/cluster-administration/logging/#log-rotation
  ///
  /// Valid format is positive number + unit, e.g. 100Ki, 10Mi. Valid units are
  /// Ki, Mi, Gi.
  /// The value must be between 10Mi and 500Mi, inclusive.
  ///
  /// Note that the total container log size (container_log_max_size *
  /// container_log_max_files) cannot exceed 1% of the total
  /// storage of the node, to avoid disk pressure caused by log files.
  ///
  /// The default value is 10Mi if unspecified.
  public var containerLogMaxSize: Swift.String = Swift.String()

  /// Optional. Defines the maximum number of container log files that can be
  /// present for a container. See
  /// https://kubernetes.io/docs/concepts/cluster-administration/logging/#log-rotation
  ///
  /// The value must be an integer between 2 and 10, inclusive.
  /// The default value is 5 if unspecified.
  public var containerLogMaxFiles: Swift.Int32 = Swift.Int32()

  /// Optional. Defines a comma-separated allowlist of unsafe sysctls or sysctl
  /// patterns (ending in `*`).
  ///
  /// The unsafe namespaced sysctl groups are `kernel.shm*`, `kernel.msg*`,
  /// `kernel.sem`, `fs.mqueue.*`, and `net.*`. Leaving this allowlist empty
  /// means they cannot be set on Pods.
  ///
  /// To allow certain sysctls or sysctl patterns to be set on Pods, list them
  /// separated by commas.
  /// For example: `kernel.msg*,net.ipv4.route.min_pmtu`.
  ///
  /// See https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/
  /// for more details.
  public var allowedUnsafeSysctls: [Swift.String] = []

  /// Optional. eviction_soft is a map of signal names to quantities that defines
  /// soft eviction thresholds. Each signal is compared to its corresponding
  /// threshold to determine if a pod eviction should occur.
  public var evictionSoft: EvictionSignals? = nil

  /// Optional. eviction_soft_grace_period is a map of signal names to quantities
  /// that defines grace periods for each soft eviction signal. The grace period
  /// is the amount of time that a pod must be under pressure before an eviction
  /// occurs.
  public var evictionSoftGracePeriod: EvictionGracePeriod? = nil

  /// Optional. eviction_minimum_reclaim is a map of signal names to quantities
  /// that defines minimum reclaims, which describe the minimum amount of a given
  /// resource the kubelet will reclaim when performing a pod eviction while that
  /// resource is under pressure.
  public var evictionMinimumReclaim: EvictionMinimumReclaim? = nil

  /// Optional. eviction_max_pod_grace_period_seconds is the maximum allowed
  /// grace period (in seconds) to use when terminating pods in response to a
  /// soft eviction threshold being met. This value effectively caps the Pod's
  /// terminationGracePeriodSeconds value during soft evictions. Default: 0.
  /// Range: [0, 300].
  public var evictionMaxPodGracePeriodSeconds: Swift.Int32 = Swift.Int32()

  /// Optional. Defines the maximum number of image pulls in parallel.
  /// The range is 2 to 5, inclusive.
  /// The default value is 2 or 3 depending on the disk type.
  ///
  /// See
  /// https://kubernetes.io/docs/concepts/containers/images/#maximum-parallel-image-pulls
  /// for more details.
  public var maxParallelImagePulls: Swift.Int32 = Swift.Int32()

  /// Optional. Defines whether to enable single process OOM killer.
  /// If true, will prevent the memory.oom.group flag from being set for
  /// container cgroups in cgroups v2. This causes processes in the container to
  /// be OOM killed individually instead of as a group.
  public var singleProcessOomKill: Swift.Bool? = nil

  /// Optional. Contains configuration options to modify node-level parameters
  /// for container restart behavior.
  public var crashLoopBackOff: NodeKubeletConfig.CrashLoopBackOffConfig? = nil

  /// Optional. shutdown_grace_period_seconds is the maximum allowed grace period
  /// (in seconds) the total duration that the node should delay the shutdown
  /// during a graceful shutdown. This is the total grace period for pod
  /// termination for both regular and critical pods.
  /// https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/
  /// If set to 0, node will not enable the graceful node shutdown functionality.
  /// This field is only valid for Spot VMs.
  /// Allowed values: 0, 30, 120.
  public var shutdownGracePeriodSeconds: Swift.Int32? = nil

  /// Optional. shutdown_grace_period_critical_pods_seconds is the maximum
  /// allowed grace period (in seconds) used to terminate critical pods during a
  /// node shutdown. This value should be <= shutdown_grace_period_seconds, and
  /// is only valid if shutdown_grace_period_seconds is set.
  /// https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/
  /// Range: [0, 120].
  public var shutdownGracePeriodCriticalPodsSeconds: Swift.Int32? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `NodeKubeletConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodeKubeletConfig().with { $0.cpuManagerPolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cpuManagerPolicy = CodingKeys(stringValue: "cpuManagerPolicy")
    static let topologyManager = CodingKeys(stringValue: "topologyManager")
    static let memoryManager = CodingKeys(stringValue: "memoryManager")
    static let cpuCfsQuota = CodingKeys(stringValue: "cpuCfsQuota")
    static let cpuCfsQuotaPeriod = CodingKeys(stringValue: "cpuCfsQuotaPeriod")
    static let podPidsLimit = CodingKeys(stringValue: "podPidsLimit")
    static let insecureKubeletReadonlyPortEnabled = CodingKeys(
      stringValue: "insecureKubeletReadonlyPortEnabled")
    static let imageGcLowThresholdPercent = CodingKeys(stringValue: "imageGcLowThresholdPercent")
    static let imageGcHighThresholdPercent = CodingKeys(stringValue: "imageGcHighThresholdPercent")
    static let imageMinimumGcAge = CodingKeys(stringValue: "imageMinimumGcAge")
    static let imageMaximumGcAge = CodingKeys(stringValue: "imageMaximumGcAge")
    static let containerLogMaxSize = CodingKeys(stringValue: "containerLogMaxSize")
    static let containerLogMaxFiles = CodingKeys(stringValue: "containerLogMaxFiles")
    static let allowedUnsafeSysctls = CodingKeys(stringValue: "allowedUnsafeSysctls")
    static let evictionSoft = CodingKeys(stringValue: "evictionSoft")
    static let evictionSoftGracePeriod = CodingKeys(stringValue: "evictionSoftGracePeriod")
    static let evictionMinimumReclaim = CodingKeys(stringValue: "evictionMinimumReclaim")
    static let evictionMaxPodGracePeriodSeconds = CodingKeys(
      stringValue: "evictionMaxPodGracePeriodSeconds")
    static let maxParallelImagePulls = CodingKeys(stringValue: "maxParallelImagePulls")
    static let singleProcessOomKill = CodingKeys(stringValue: "singleProcessOomKill")
    static let crashLoopBackOff = CodingKeys(stringValue: "crashLoopBackOff")
    static let shutdownGracePeriodSeconds = CodingKeys(stringValue: "shutdownGracePeriodSeconds")
    static let shutdownGracePeriodCriticalPodsSeconds = CodingKeys(
      stringValue: "shutdownGracePeriodCriticalPodsSeconds")

    static let _knownKeys: Set<Swift.String> = [
      "cpuManagerPolicy",
      "topologyManager",
      "memoryManager",
      "cpuCfsQuota",
      "cpuCfsQuotaPeriod",
      "podPidsLimit",
      "insecureKubeletReadonlyPortEnabled",
      "imageGcLowThresholdPercent",
      "imageGcHighThresholdPercent",
      "imageMinimumGcAge",
      "imageMaximumGcAge",
      "containerLogMaxSize",
      "containerLogMaxFiles",
      "allowedUnsafeSysctls",
      "evictionSoft",
      "evictionSoftGracePeriod",
      "evictionMinimumReclaim",
      "evictionMaxPodGracePeriodSeconds",
      "maxParallelImagePulls",
      "singleProcessOomKill",
      "crashLoopBackOff",
      "shutdownGracePeriodSeconds",
      "shutdownGracePeriodCriticalPodsSeconds",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cpuManagerPolicy) {
      self.cpuManagerPolicy = value
    }
    self.topologyManager = try container.decodeIfPresent(
      TopologyManager.self, forKey: .topologyManager)
    self.memoryManager = try container.decodeIfPresent(MemoryManager.self, forKey: .memoryManager)
    self.cpuCfsQuota = try container.decodeIfPresent(
      GoogleCloudWKT.BoolValue.self, forKey: .cpuCfsQuota)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cpuCfsQuotaPeriod) {
      self.cpuCfsQuotaPeriod = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .podPidsLimit) {
      self.podPidsLimit = value
    }
    self.insecureKubeletReadonlyPortEnabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .insecureKubeletReadonlyPortEnabled)
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .imageGcLowThresholdPercent)
    {
      self.imageGcLowThresholdPercent = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .imageGcHighThresholdPercent)
    {
      self.imageGcHighThresholdPercent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageMinimumGcAge) {
      self.imageMinimumGcAge = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageMaximumGcAge) {
      self.imageMaximumGcAge = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .containerLogMaxSize) {
      self.containerLogMaxSize = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .containerLogMaxFiles) {
      self.containerLogMaxFiles = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedUnsafeSysctls)
    {
      self.allowedUnsafeSysctls = value
    }
    self.evictionSoft = try container.decodeIfPresent(EvictionSignals.self, forKey: .evictionSoft)
    self.evictionSoftGracePeriod = try container.decodeIfPresent(
      EvictionGracePeriod.self, forKey: .evictionSoftGracePeriod)
    self.evictionMinimumReclaim = try container.decodeIfPresent(
      EvictionMinimumReclaim.self, forKey: .evictionMinimumReclaim)
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .evictionMaxPodGracePeriodSeconds)
    {
      self.evictionMaxPodGracePeriodSeconds = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxParallelImagePulls) {
      self.maxParallelImagePulls = value
    }
    self.singleProcessOomKill = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .singleProcessOomKill)
    self.crashLoopBackOff = try container.decodeIfPresent(
      NodeKubeletConfig.CrashLoopBackOffConfig.self, forKey: .crashLoopBackOff)
    self.shutdownGracePeriodSeconds = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .shutdownGracePeriodSeconds)
    self.shutdownGracePeriodCriticalPodsSeconds = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .shutdownGracePeriodCriticalPodsSeconds)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cpuManagerPolicy, forKey: .cpuManagerPolicy)
    try container.encodeIfPresent(self.topologyManager, forKey: .topologyManager)
    try container.encodeIfPresent(self.memoryManager, forKey: .memoryManager)
    try container.encodeIfPresent(self.cpuCfsQuota, forKey: .cpuCfsQuota)
    try container.encode(self.cpuCfsQuotaPeriod, forKey: .cpuCfsQuotaPeriod)
    try container.encode(self.podPidsLimit, forKey: .podPidsLimit)
    try container.encodeIfPresent(
      self.insecureKubeletReadonlyPortEnabled, forKey: .insecureKubeletReadonlyPortEnabled)
    try container.encode(self.imageGcLowThresholdPercent, forKey: .imageGcLowThresholdPercent)
    try container.encode(self.imageGcHighThresholdPercent, forKey: .imageGcHighThresholdPercent)
    try container.encode(self.imageMinimumGcAge, forKey: .imageMinimumGcAge)
    try container.encode(self.imageMaximumGcAge, forKey: .imageMaximumGcAge)
    try container.encode(self.containerLogMaxSize, forKey: .containerLogMaxSize)
    try container.encode(self.containerLogMaxFiles, forKey: .containerLogMaxFiles)
    try container.encode(self.allowedUnsafeSysctls, forKey: .allowedUnsafeSysctls)
    try container.encodeIfPresent(self.evictionSoft, forKey: .evictionSoft)
    try container.encodeIfPresent(self.evictionSoftGracePeriod, forKey: .evictionSoftGracePeriod)
    try container.encodeIfPresent(self.evictionMinimumReclaim, forKey: .evictionMinimumReclaim)
    try container.encode(
      self.evictionMaxPodGracePeriodSeconds, forKey: .evictionMaxPodGracePeriodSeconds)
    try container.encode(self.maxParallelImagePulls, forKey: .maxParallelImagePulls)
    try container.encodeIfPresent(self.singleProcessOomKill, forKey: .singleProcessOomKill)
    try container.encodeIfPresent(self.crashLoopBackOff, forKey: .crashLoopBackOff)
    try container.encodeIfPresent(
      self.shutdownGracePeriodSeconds, forKey: .shutdownGracePeriodSeconds)
    try container.encodeIfPresent(
      self.shutdownGracePeriodCriticalPodsSeconds, forKey: .shutdownGracePeriodCriticalPodsSeconds)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Contains config to modify node-level parameters for container restart
  /// behavior.
  public struct CrashLoopBackOffConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The maximum duration the backoff delay can accrue to for
    /// container restarts, minimum 1 second, maximum 300 seconds. If not set,
    /// defaults to the internal crashloopbackoff maximum.
    ///
    /// The string must be a sequence of decimal numbers, each with optional
    /// fraction and a unit suffix, such as "300ms".
    /// Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    ///
    /// See
    /// https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#configurable-container-restart-delay
    /// for more details.
    public var maxContainerRestartPeriod: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `CrashLoopBackOffConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CrashLoopBackOffConfig().with { $0.maxContainerRestartPeriod = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let maxContainerRestartPeriod = CodingKeys(stringValue: "maxContainerRestartPeriod")

      static let _knownKeys: Set<Swift.String> = [
        "maxContainerRestartPeriod"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .maxContainerRestartPeriod)
      {
        self.maxContainerRestartPeriod = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.maxContainerRestartPeriod, forKey: .maxContainerRestartPeriod)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.container.v1.NodeKubeletConfig.CrashLoopBackOffConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.NodeKubeletConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
