// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Node pool configs that apply to all auto-provisioned node pools
/// in autopilot clusters and node auto-provisioning enabled clusters.
public struct NodePoolAutoConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The list of instance tags applied to all nodes. Tags are used to identify
  /// valid sources or targets for network firewalls and are specified by
  /// the client during cluster creation. Each tag within the list
  /// must comply with RFC1035.
  public var networkTags: NetworkTags? = nil

  /// Resource manager tag keys and values to be attached to the nodes
  /// for managing Compute Engine firewalls using Network Firewall Policies.
  public var resourceManagerTags: ResourceManagerTags? = nil

  /// NodeKubeletConfig controls the defaults for autoprovisioned node-pools.
  ///
  /// Currently only `insecure_kubelet_readonly_port_enabled` can be set here.
  public var nodeKubeletConfig: NodeKubeletConfig? = nil

  /// Output only. Configuration options for Linux nodes.
  public var linuxNodeConfig: LinuxNodeConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `NodePoolAutoConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodePoolAutoConfig().with { $0.networkTags = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let networkTags = CodingKeys(stringValue: "networkTags")
    static let resourceManagerTags = CodingKeys(stringValue: "resourceManagerTags")
    static let nodeKubeletConfig = CodingKeys(stringValue: "nodeKubeletConfig")
    static let linuxNodeConfig = CodingKeys(stringValue: "linuxNodeConfig")

    static let _knownKeys: Set<Swift.String> = [
      "networkTags",
      "resourceManagerTags",
      "nodeKubeletConfig",
      "linuxNodeConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.networkTags = try container.decodeIfPresent(NetworkTags.self, forKey: .networkTags)
    self.resourceManagerTags = try container.decodeIfPresent(
      ResourceManagerTags.self, forKey: .resourceManagerTags)
    self.nodeKubeletConfig = try container.decodeIfPresent(
      NodeKubeletConfig.self, forKey: .nodeKubeletConfig)
    self.linuxNodeConfig = try container.decodeIfPresent(
      LinuxNodeConfig.self, forKey: .linuxNodeConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.networkTags, forKey: .networkTags)
    try container.encodeIfPresent(self.resourceManagerTags, forKey: .resourceManagerTags)
    try container.encodeIfPresent(self.nodeKubeletConfig, forKey: .nodeKubeletConfig)
    try container.encodeIfPresent(self.linuxNodeConfig, forKey: .linuxNodeConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.NodePoolAutoConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
