// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Subset of NodeConfig message that has defaults.
public struct NodeConfigDefaults: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// GCFS (Google Container File System, also known as Riptide) options.
  public var gcfsConfig: GcfsConfig? = nil

  /// Logging configuration for node pools.
  public var loggingConfig: NodePoolLoggingConfig? = nil

  /// Parameters for containerd customization.
  public var containerdConfig: ContainerdConfig? = nil

  /// NodeKubeletConfig controls the defaults for new node-pools.
  ///
  /// Currently only `insecure_kubelet_readonly_port_enabled` can be set here.
  public var nodeKubeletConfig: NodeKubeletConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NodeConfigDefaults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodeConfigDefaults().with { $0.gcfsConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcfsConfig = CodingKeys(stringValue: "gcfsConfig")
    static let loggingConfig = CodingKeys(stringValue: "loggingConfig")
    static let containerdConfig = CodingKeys(stringValue: "containerdConfig")
    static let nodeKubeletConfig = CodingKeys(stringValue: "nodeKubeletConfig")

    static let _knownKeys: Set<Swift.String> = [
      "gcfsConfig",
      "loggingConfig",
      "containerdConfig",
      "nodeKubeletConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.gcfsConfig = try container.decodeIfPresent(GcfsConfig.self, forKey: .gcfsConfig)
    self.loggingConfig = try container.decodeIfPresent(
      NodePoolLoggingConfig.self, forKey: .loggingConfig)
    self.containerdConfig = try container.decodeIfPresent(
      ContainerdConfig.self, forKey: .containerdConfig)
    self.nodeKubeletConfig = try container.decodeIfPresent(
      NodeKubeletConfig.self, forKey: .nodeKubeletConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.gcfsConfig, forKey: .gcfsConfig)
    try container.encodeIfPresent(self.loggingConfig, forKey: .loggingConfig)
    try container.encodeIfPresent(self.containerdConfig, forKey: .containerdConfig)
    try container.encodeIfPresent(self.nodeKubeletConfig, forKey: .nodeKubeletConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.NodeConfigDefaults"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
