// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// PrivilegedAdmissionConfig stores the list of authorized allowlist
/// paths for the cluster.
public struct PrivilegedAdmissionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The customer allowlist Cloud Storage paths for the cluster. These paths are
  /// used with the `--autopilot-privileged-admission` flag to authorize
  /// privileged workloads in Autopilot clusters.
  ///
  /// Paths can be GKE-owned, in the format
  /// `gke://<partner_name>/<app_name>/<allowlist_path>`, or customer-owned, in
  /// the format `gs://<bucket_name>/<allowlist_path>`.
  ///
  /// Wildcards (`*`) are supported to authorize all allowlists under specific
  /// paths or directories. Example: `gs://my-bucket/*` will authorize all
  /// allowlists under the `my-bucket` bucket.
  public var allowlistPaths: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PrivilegedAdmissionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivilegedAdmissionConfig().with { $0.allowlistPaths = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allowlistPaths = CodingKeys(stringValue: "allowlistPaths")

    static let _knownKeys: Set<Swift.String> = [
      "allowlistPaths"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowlistPaths) {
      self.allowlistPaths = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.allowlistPaths, forKey: .allowlistPaths)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.PrivilegedAdmissionConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
