// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents an arbitrary window of time that recurs.
public struct RecurringTimeWindow: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The window of the first recurrence.
  public var window: TimeWindow? = nil

  /// An RRULE (https://tools.ietf.org/html/rfc5545#section-3.8.5.3) for how
  /// this window recurs. They go on for the span of time between the start and
  /// end time.
  ///
  /// For example, to have something repeat every weekday, you'd use:
  /// `FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR`
  ///
  /// To repeat some window daily (equivalent to the DailyMaintenanceWindow):
  /// `FREQ=DAILY`
  ///
  /// For the first weekend of every month:
  /// `FREQ=MONTHLY;BYSETPOS=1;BYDAY=SA,SU`
  ///
  /// This specifies how frequently the window starts. Eg, if you wanted to have
  /// a 9-5 UTC-4 window every weekday, you'd use something like:
  /// ```
  /// start time = 2019-01-01T09:00:00-0400
  /// end time = 2019-01-01T17:00:00-0400
  /// recurrence = FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
  /// ```
  ///
  /// Windows can span multiple days. Eg, to make the window encompass every
  /// weekend from midnight Saturday till the last minute of Sunday UTC:
  /// ```
  /// start time = 2019-01-05T00:00:00Z
  /// end time = 2019-01-07T23:59:00Z
  /// recurrence = FREQ=WEEKLY;BYDAY=SA
  /// ```
  ///
  /// Note the start and end time's specific dates are largely arbitrary except
  /// to specify duration of the window and when it first starts.
  /// The FREQ values of HOURLY, MINUTELY, and SECONDLY are not supported.
  public var recurrence: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RecurringTimeWindow`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecurringTimeWindow().with { $0.window = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let window = CodingKeys(stringValue: "window")
    static let recurrence = CodingKeys(stringValue: "recurrence")

    static let _knownKeys: Set<Swift.String> = [
      "window",
      "recurrence",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.window = try container.decodeIfPresent(TimeWindow.self, forKey: .window)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recurrence) {
      self.recurrence = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.window, forKey: .window)
    try container.encode(self.recurrence, forKey: .recurrence)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.RecurringTimeWindow"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
