// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Represents an arbitrary window of time that recurs.
/// Will replace RecurringTimeWindow.
public struct RecurringMaintenanceWindow: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Specifies the date before which will not be scheduled.
  /// Depending on the recurrence, this may be the date the first window appears.
  /// Days are measured in the UTC timezone. This setting must be used when
  /// INTERVAL>1 or FREQ=WEEKLY/MONTHLY and no BYDAY specified.
  public var delayUntil: GoogleType.Date? = nil

  /// Required. Start time of the window on days that it is scheduled,
  /// assuming UTC timezone.
  public var windowStartTime: GoogleType.TimeOfDay? = nil

  /// Required. Duration of the window.
  public var windowDuration: GoogleCloudWKT.Duration? = nil

  /// Required. An RRULE (https://tools.ietf.org/html/rfc5545#section-3.8.5.3)
  /// for how this window recurs.
  ///
  /// For example, to have something repeat every weekday, you'd use:
  /// `FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR`
  ///
  /// To repeat some window daily (equivalent to the DailyMaintenanceWindow):
  /// `FREQ=DAILY`
  ///
  /// For the first weekend of every month:
  /// `FREQ=MONTHLY;BYSETPOS=1;BYDAY=SA,SU`
  ///
  /// The FREQ values of HOURLY, MINUTELY, and SECONDLY are not supported.
  public var recurrence: Swift.String = Swift.String()

  /// Initialize a new instance of `RecurringMaintenanceWindow`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecurringMaintenanceWindow().with { $0.delayUntil = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.RecurringMaintenanceWindow"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
