// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for exporting cluster resource usages.
public struct ResourceUsageExportConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Configuration to use BigQuery as usage export destination.
  public var bigqueryDestination: ResourceUsageExportConfig.BigQueryDestination? = nil

  /// Whether to enable network egress metering for this cluster. If enabled, a
  /// daemonset will be created in the cluster to meter network egress traffic.
  public var enableNetworkEgressMetering: Swift.Bool = Swift.Bool()

  /// Configuration to enable resource consumption metering.
  public var consumptionMeteringConfig: ResourceUsageExportConfig.ConsumptionMeteringConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceUsageExportConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceUsageExportConfig().with { $0.bigqueryDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let bigqueryDestination = CodingKeys(stringValue: "bigqueryDestination")
    static let enableNetworkEgressMetering = CodingKeys(stringValue: "enableNetworkEgressMetering")
    static let consumptionMeteringConfig = CodingKeys(stringValue: "consumptionMeteringConfig")

    static let _knownKeys: Set<Swift.String> = [
      "bigqueryDestination",
      "enableNetworkEgressMetering",
      "consumptionMeteringConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.bigqueryDestination = try container.decodeIfPresent(
      ResourceUsageExportConfig.BigQueryDestination.self, forKey: .bigqueryDestination)
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableNetworkEgressMetering)
    {
      self.enableNetworkEgressMetering = value
    }
    self.consumptionMeteringConfig = try container.decodeIfPresent(
      ResourceUsageExportConfig.ConsumptionMeteringConfig.self, forKey: .consumptionMeteringConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.bigqueryDestination, forKey: .bigqueryDestination)
    try container.encode(self.enableNetworkEgressMetering, forKey: .enableNetworkEgressMetering)
    try container.encodeIfPresent(
      self.consumptionMeteringConfig, forKey: .consumptionMeteringConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Parameters for using BigQuery as the destination of resource usage export.
  public struct BigQueryDestination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The ID of a BigQuery Dataset.
    public var datasetId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BigQueryDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BigQueryDestination().with { $0.datasetId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let datasetId = CodingKeys(stringValue: "datasetId")

      static let _knownKeys: Set<Swift.String> = [
        "datasetId"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .datasetId) {
        self.datasetId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.datasetId, forKey: .datasetId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.container.v1.ResourceUsageExportConfig.BigQueryDestination"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters for controlling consumption metering.
  public struct ConsumptionMeteringConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Whether to enable consumption metering for this cluster. If enabled, a
    /// second BigQuery table will be created to hold resource consumption
    /// records.
    public var enabled: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConsumptionMeteringConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConsumptionMeteringConfig().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enabled = CodingKeys(stringValue: "enabled")

      static let _knownKeys: Set<Swift.String> = [
        "enabled"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
        self.enabled = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enabled, forKey: .enabled)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.container.v1.ResourceUsageExportConfig.ConsumptionMeteringConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.ResourceUsageExportConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
