// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// SecurityBulletinEvent is a notification sent to customers when a security
/// bulletin has been posted that they are vulnerable to.
public struct SecurityBulletinEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource type (node/control plane) that has the vulnerability. Multiple
  /// notifications (1 notification per resource type) will be sent for a
  /// vulnerability that affects > 1 resource type.
  public var resourceTypeAffected: Swift.String = Swift.String()

  /// The ID of the bulletin corresponding to the vulnerability.
  public var bulletinId: Swift.String = Swift.String()

  /// The CVEs associated with this bulletin.
  public var cveIds: [Swift.String] = []

  /// The severity of this bulletin as it relates to GKE.
  public var severity: Swift.String = Swift.String()

  /// The URI link to the bulletin on the website for more information.
  public var bulletinUri: Swift.String = Swift.String()

  /// A brief description of the bulletin. See the bulletin pointed to by the
  /// bulletin_uri field for an expanded description.
  public var briefDescription: Swift.String = Swift.String()

  /// The GKE minor versions affected by this vulnerability.
  public var affectedSupportedMinors: [Swift.String] = []

  /// The GKE versions where this vulnerability is patched.
  public var patchedVersions: [Swift.String] = []

  /// This represents a version selected from the patched_versions field that
  /// the cluster receiving this notification should most likely want to upgrade
  /// to based on its current version. Note that if this notification is being
  /// received by a given cluster, it means that this version is currently
  /// available as an upgrade target in that cluster's location.
  public var suggestedUpgradeTarget: Swift.String = Swift.String()

  /// If this field is specified, it means there are manual steps that the user
  /// must take to make their clusters safe.
  public var manualStepsRequired: Swift.Bool = Swift.Bool()

  /// The GKE versions where this vulnerability is mitigated.
  public var mitigatedVersions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SecurityBulletinEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecurityBulletinEvent().with { $0.resourceTypeAffected = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resourceTypeAffected = CodingKeys(stringValue: "resourceTypeAffected")
    static let bulletinId = CodingKeys(stringValue: "bulletinId")
    static let cveIds = CodingKeys(stringValue: "cveIds")
    static let severity = CodingKeys(stringValue: "severity")
    static let bulletinUri = CodingKeys(stringValue: "bulletinUri")
    static let briefDescription = CodingKeys(stringValue: "briefDescription")
    static let affectedSupportedMinors = CodingKeys(stringValue: "affectedSupportedMinors")
    static let patchedVersions = CodingKeys(stringValue: "patchedVersions")
    static let suggestedUpgradeTarget = CodingKeys(stringValue: "suggestedUpgradeTarget")
    static let manualStepsRequired = CodingKeys(stringValue: "manualStepsRequired")
    static let mitigatedVersions = CodingKeys(stringValue: "mitigatedVersions")

    static let _knownKeys: Set<Swift.String> = [
      "resourceTypeAffected",
      "bulletinId",
      "cveIds",
      "severity",
      "bulletinUri",
      "briefDescription",
      "affectedSupportedMinors",
      "patchedVersions",
      "suggestedUpgradeTarget",
      "manualStepsRequired",
      "mitigatedVersions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceTypeAffected) {
      self.resourceTypeAffected = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .bulletinId) {
      self.bulletinId = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .cveIds) {
      self.cveIds = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .severity) {
      self.severity = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .bulletinUri) {
      self.bulletinUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .briefDescription) {
      self.briefDescription = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .affectedSupportedMinors)
    {
      self.affectedSupportedMinors = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .patchedVersions) {
      self.patchedVersions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .suggestedUpgradeTarget)
    {
      self.suggestedUpgradeTarget = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .manualStepsRequired) {
      self.manualStepsRequired = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .mitigatedVersions) {
      self.mitigatedVersions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.resourceTypeAffected, forKey: .resourceTypeAffected)
    try container.encode(self.bulletinId, forKey: .bulletinId)
    try container.encode(self.cveIds, forKey: .cveIds)
    try container.encode(self.severity, forKey: .severity)
    try container.encode(self.bulletinUri, forKey: .bulletinUri)
    try container.encode(self.briefDescription, forKey: .briefDescription)
    try container.encode(self.affectedSupportedMinors, forKey: .affectedSupportedMinors)
    try container.encode(self.patchedVersions, forKey: .patchedVersions)
    try container.encode(self.suggestedUpgradeTarget, forKey: .suggestedUpgradeTarget)
    try container.encode(self.manualStepsRequired, forKey: .manualStepsRequired)
    try container.encode(self.mitigatedVersions, forKey: .mitigatedVersions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.SecurityBulletinEvent"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
