// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Kubernetes Engine service configuration.
public struct ServerConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Version of Kubernetes the service deploys by default.
  public var defaultClusterVersion: Swift.String = Swift.String()

  /// List of valid node upgrade target versions, in descending order.
  public var validNodeVersions: [Swift.String] = []

  /// Default image type.
  public var defaultImageType: Swift.String = Swift.String()

  /// List of valid image types.
  public var validImageTypes: [Swift.String] = []

  /// List of valid master versions, in descending order.
  public var validMasterVersions: [Swift.String] = []

  /// List of release channel configurations.
  public var channels: [ServerConfig.ReleaseChannelConfig] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServerConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServerConfig().with { $0.defaultClusterVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let defaultClusterVersion = CodingKeys(stringValue: "defaultClusterVersion")
    static let validNodeVersions = CodingKeys(stringValue: "validNodeVersions")
    static let defaultImageType = CodingKeys(stringValue: "defaultImageType")
    static let validImageTypes = CodingKeys(stringValue: "validImageTypes")
    static let validMasterVersions = CodingKeys(stringValue: "validMasterVersions")
    static let channels = CodingKeys(stringValue: "channels")

    static let _knownKeys: Set<Swift.String> = [
      "defaultClusterVersion",
      "validNodeVersions",
      "defaultImageType",
      "validImageTypes",
      "validMasterVersions",
      "channels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultClusterVersion)
    {
      self.defaultClusterVersion = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .validNodeVersions) {
      self.validNodeVersions = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultImageType) {
      self.defaultImageType = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .validImageTypes) {
      self.validImageTypes = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .validMasterVersions)
    {
      self.validMasterVersions = value
    }
    if let value = try container.decodeIfPresent(
      [ServerConfig.ReleaseChannelConfig].self, forKey: .channels)
    {
      self.channels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.defaultClusterVersion, forKey: .defaultClusterVersion)
    try container.encode(self.validNodeVersions, forKey: .validNodeVersions)
    try container.encode(self.defaultImageType, forKey: .defaultImageType)
    try container.encode(self.validImageTypes, forKey: .validImageTypes)
    try container.encode(self.validMasterVersions, forKey: .validMasterVersions)
    try container.encode(self.channels, forKey: .channels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// ReleaseChannelConfig exposes configuration for a release channel.
  public struct ReleaseChannelConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The release channel this configuration applies to.
    public var channel: ReleaseChannel.Channel = ReleaseChannel.Channel()

    /// The default version for newly created clusters on the channel.
    public var defaultVersion: Swift.String = Swift.String()

    /// List of valid versions for the channel.
    public var validVersions: [Swift.String] = []

    /// The auto upgrade target version for clusters on the channel.
    public var upgradeTargetVersion: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ReleaseChannelConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReleaseChannelConfig().with { $0.channel = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let channel = CodingKeys(stringValue: "channel")
      static let defaultVersion = CodingKeys(stringValue: "defaultVersion")
      static let validVersions = CodingKeys(stringValue: "validVersions")
      static let upgradeTargetVersion = CodingKeys(stringValue: "upgradeTargetVersion")

      static let _knownKeys: Set<Swift.String> = [
        "channel",
        "defaultVersion",
        "validVersions",
        "upgradeTargetVersion",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(ReleaseChannel.Channel.self, forKey: .channel) {
        self.channel = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .defaultVersion) {
        self.defaultVersion = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .validVersions) {
        self.validVersions = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .upgradeTargetVersion)
      {
        self.upgradeTargetVersion = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.channel, forKey: .channel)
      try container.encode(self.defaultVersion, forKey: .defaultVersion)
      try container.encode(self.validVersions, forKey: .validVersions)
      try container.encode(self.upgradeTargetVersion, forKey: .upgradeTargetVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.container.v1.ServerConfig.ReleaseChannelConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.ServerConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
