// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// UsableSubnetwork resource returns the subnetwork name, its associated network
/// and the primary CIDR range.
public struct UsableSubnetwork: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Subnetwork Name.
  /// Example: projects/my-project/regions/us-central1/subnetworks/my-subnet
  public var subnetwork: Swift.String = Swift.String()

  /// Network Name.
  /// Example: projects/my-project/global/networks/my-network
  public var network: Swift.String = Swift.String()

  /// The range of internal addresses that are owned by this subnetwork.
  public var ipCidrRange: Swift.String = Swift.String()

  /// Secondary IP ranges.
  public var secondaryIpRanges: [UsableSubnetworkSecondaryRange] = []

  /// A human readable status message representing the reasons for cases where
  /// the caller cannot use the secondary ranges under the subnet. For example if
  /// the secondary_ip_ranges is empty due to a permission issue, an insufficient
  /// permission message will be given by status_message.
  public var statusMessage: Swift.String = Swift.String()

  /// Initialize a new instance of `UsableSubnetwork`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UsableSubnetwork().with { $0.subnetwork = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.UsableSubnetwork"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
