// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// UserManagedKeysConfig holds the resource address to Keys which are used
/// for signing certs and token that are used for communication within cluster.
public struct UserManagedKeysConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Certificate Authority Service caPool to use for the cluster CA in this
  /// cluster.
  public var clusterCa: Swift.String = Swift.String()

  /// Resource path of the Certificate Authority Service caPool to use for the
  /// etcd API CA in this cluster.
  public var etcdApiCa: Swift.String = Swift.String()

  /// Resource path of the Certificate Authority Service caPool to use for the
  /// etcd peer CA in this cluster.
  public var etcdPeerCa: Swift.String = Swift.String()

  /// The Cloud KMS cryptoKeyVersions to use for signing service account JWTs
  /// issued by this cluster.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion}`
  public var serviceAccountSigningKeys: [Swift.String] = []

  /// The Cloud KMS cryptoKeyVersions to use for verifying service account JWTs
  /// issued by this cluster.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion}`
  public var serviceAccountVerificationKeys: [Swift.String] = []

  /// The Certificate Authority Service caPool to use for the aggregation CA in
  /// this cluster.
  public var aggregationCa: Swift.String = Swift.String()

  /// The Cloud KMS cryptoKey to use for Confidential Hyperdisk on the control
  /// plane nodes.
  public var controlPlaneDiskEncryptionKey: Swift.String = Swift.String()

  /// Output only. All of the versions of the Cloud KMS cryptoKey that are used
  /// by Confidential Hyperdisks on the control plane nodes.
  public var controlPlaneDiskEncryptionKeyVersions: [Swift.String] = []

  /// Resource path of the Cloud KMS cryptoKey to use for encryption of internal
  /// etcd backups.
  public var gkeopsEtcdBackupEncryptionKey: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UserManagedKeysConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserManagedKeysConfig().with { $0.clusterCa = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let clusterCa = CodingKeys(stringValue: "clusterCa")
    static let etcdApiCa = CodingKeys(stringValue: "etcdApiCa")
    static let etcdPeerCa = CodingKeys(stringValue: "etcdPeerCa")
    static let serviceAccountSigningKeys = CodingKeys(stringValue: "serviceAccountSigningKeys")
    static let serviceAccountVerificationKeys = CodingKeys(
      stringValue: "serviceAccountVerificationKeys")
    static let aggregationCa = CodingKeys(stringValue: "aggregationCa")
    static let controlPlaneDiskEncryptionKey = CodingKeys(
      stringValue: "controlPlaneDiskEncryptionKey")
    static let controlPlaneDiskEncryptionKeyVersions = CodingKeys(
      stringValue: "controlPlaneDiskEncryptionKeyVersions")
    static let gkeopsEtcdBackupEncryptionKey = CodingKeys(
      stringValue: "gkeopsEtcdBackupEncryptionKey")

    static let _knownKeys: Set<Swift.String> = [
      "clusterCa",
      "etcdApiCa",
      "etcdPeerCa",
      "serviceAccountSigningKeys",
      "serviceAccountVerificationKeys",
      "aggregationCa",
      "controlPlaneDiskEncryptionKey",
      "controlPlaneDiskEncryptionKeyVersions",
      "gkeopsEtcdBackupEncryptionKey",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterCa) {
      self.clusterCa = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etcdApiCa) {
      self.etcdApiCa = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etcdPeerCa) {
      self.etcdPeerCa = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .serviceAccountSigningKeys)
    {
      self.serviceAccountSigningKeys = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .serviceAccountVerificationKeys)
    {
      self.serviceAccountVerificationKeys = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .aggregationCa) {
      self.aggregationCa = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .controlPlaneDiskEncryptionKey)
    {
      self.controlPlaneDiskEncryptionKey = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .controlPlaneDiskEncryptionKeyVersions)
    {
      self.controlPlaneDiskEncryptionKeyVersions = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .gkeopsEtcdBackupEncryptionKey)
    {
      self.gkeopsEtcdBackupEncryptionKey = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.clusterCa, forKey: .clusterCa)
    try container.encode(self.etcdApiCa, forKey: .etcdApiCa)
    try container.encode(self.etcdPeerCa, forKey: .etcdPeerCa)
    try container.encode(self.serviceAccountSigningKeys, forKey: .serviceAccountSigningKeys)
    try container.encode(
      self.serviceAccountVerificationKeys, forKey: .serviceAccountVerificationKeys)
    try container.encode(self.aggregationCa, forKey: .aggregationCa)
    try container.encode(self.controlPlaneDiskEncryptionKey, forKey: .controlPlaneDiskEncryptionKey)
    try container.encode(
      self.controlPlaneDiskEncryptionKeyVersions, forKey: .controlPlaneDiskEncryptionKeyVersions)
    try container.encode(self.gkeopsEtcdBackupEncryptionKey, forKey: .gkeopsEtcdBackupEncryptionKey)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.UserManagedKeysConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
