// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// AcceleratorConfig represents a Hardware Accelerator request.
public struct AcceleratorConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The number of the accelerator cards exposed to an instance.
  public var acceleratorCount: Swift.Int64 = Swift.Int64()

  /// The accelerator type resource name. List of supported accelerators
  /// [here](https://cloud.google.com/compute/docs/gpus)
  public var acceleratorType: Swift.String = Swift.String()

  /// Size of partitions to create on the GPU. Valid values are described in the
  /// NVIDIA [mig user
  /// guide](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#partitioning).
  public var gpuPartitionSize: Swift.String = Swift.String()

  /// The configuration for GPU sharing options.
  public var gpuSharingConfig: GPUSharingConfig? = nil

  /// The configuration for auto installation of GPU driver.
  public var gpuDriverInstallationConfig: GPUDriverInstallationConfig? = nil

  /// Initialize a new instance of `AcceleratorConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AcceleratorConfig().with { $0.acceleratorCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.AcceleratorConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
