// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// AdditionalNodeNetworkConfig is the configuration for additional node networks
/// within the NodeNetworkConfig message
public struct AdditionalNodeNetworkConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the VPC where the additional interface belongs
  public var network: Swift.String

  /// Name of the subnetwork where the additional interface belongs
  public var subnetwork: Swift.String

  /// Initialize a new instance of `AdditionalNodeNetworkConfig`.
  public init(
    network: Swift.String = Swift.String(),
    subnetwork: Swift.String = Swift.String(),
  ) {
    self.network = network
    self.subnetwork = subnetwork
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.AdditionalNodeNetworkConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
