// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// AutoIpamConfig contains all information related to Auto IPAM
public struct AutoIpamConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The flag that enables Auto IPAM on this cluster
  public var enabled: Swift.Bool?

  /// Initialize a new instance of `AutoIpamConfig`.
  public init(
    enabled: Swift.Bool? = nil,
  ) {
    self.enabled = enabled
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.AutoIpamConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
