// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ClusterPolicyConfig stores the configuration for cluster wide policies.
public struct ClusterPolicyConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Denotes that preventing creation and mutation of resources in GKE
  /// managed namespaces and cluster-scoped GKE managed resources .
  public var noSystemMutation: Swift.Bool?

  /// Denotes preventing impersonation and CSRs for GKE System users.
  public var noSystemImpersonation: Swift.Bool?

  /// Denotes preventing unsafe webhooks.
  public var noUnsafeWebhooks: Swift.Bool?

  /// Denotes preventing standard node pools and requiring only autopilot node
  /// pools.
  public var noStandardNodePools: Swift.Bool?

  /// Initialize a new instance of `ClusterPolicyConfig`.
  public init(
    noSystemMutation: Swift.Bool? = nil,
    noSystemImpersonation: Swift.Bool? = nil,
    noUnsafeWebhooks: Swift.Bool? = nil,
    noStandardNodePools: Swift.Bool? = nil,
  ) {
    self.noSystemMutation = noSystemMutation
    self.noSystemImpersonation = noSystemImpersonation
    self.noUnsafeWebhooks = noUnsafeWebhooks
    self.noStandardNodePools = noStandardNodePools
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.ClusterPolicyConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
