// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ClusterAutoscaling contains global, per-cluster information
/// required by Cluster Autoscaler to automatically adjust
/// the size of the cluster and create/delete
/// node pools based on the current needs.
public struct ClusterAutoscaling: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Enables automatic node pool creation and deletion.
  public var enableNodeAutoprovisioning: Swift.Bool

  /// Contains global constraints regarding minimum and maximum
  /// amount of resources in the cluster.
  public var resourceLimits: [ResourceLimit]

  /// Defines autoscaling behaviour.
  public var autoscalingProfile: ClusterAutoscaling.AutoscalingProfile

  /// AutoprovisioningNodePoolDefaults contains defaults for a node pool
  /// created by NAP.
  public var autoprovisioningNodePoolDefaults: AutoprovisioningNodePoolDefaults?

  /// The list of Google Compute Engine
  /// [zones](https://cloud.google.com/compute/docs/zones#available)
  /// in which the NodePool's nodes can be created by NAP.
  public var autoprovisioningLocations: [Swift.String]

  /// Default compute class is a configuration for default compute class.
  public var defaultComputeClassConfig: DefaultComputeClassConfig?

  /// Autopilot general profile for the cluster, which defines the
  /// configuration for the cluster.
  public var autopilotGeneralProfile: ClusterAutoscaling.AutopilotGeneralProfile

  /// Initialize a new instance of `ClusterAutoscaling`.
  public init(
    enableNodeAutoprovisioning: Swift.Bool = Swift.Bool(),
    resourceLimits: [ResourceLimit] = [],
    autoscalingProfile: ClusterAutoscaling.AutoscalingProfile =
      ClusterAutoscaling.AutoscalingProfile(),
    autoprovisioningNodePoolDefaults: AutoprovisioningNodePoolDefaults? = nil,
    autoprovisioningLocations: [Swift.String] = [],
    defaultComputeClassConfig: DefaultComputeClassConfig? = nil,
    autopilotGeneralProfile: ClusterAutoscaling.AutopilotGeneralProfile =
      ClusterAutoscaling.AutopilotGeneralProfile(),
  ) {
    self.enableNodeAutoprovisioning = enableNodeAutoprovisioning
    self.resourceLimits = resourceLimits
    self.autoscalingProfile = autoscalingProfile
    self.autoprovisioningNodePoolDefaults = autoprovisioningNodePoolDefaults
    self.autoprovisioningLocations = autoprovisioningLocations
    self.defaultComputeClassConfig = defaultComputeClassConfig
    self.autopilotGeneralProfile = autopilotGeneralProfile
  }

  /// Defines possible options for autoscaling_profile field.
  public enum AutoscalingProfile: Codable, Equatable, Sendable {
    case profileUnspecified
    case optimizeUtilization
    case balanced
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .profileUnspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .profileUnspecified: return 0
      case .optimizeUtilization: return 1
      case .balanced: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .profileUnspecified: return "PROFILE_UNSPECIFIED"
      case .optimizeUtilization: return "OPTIMIZE_UTILIZATION"
      case .balanced: return "BALANCED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "PROFILE_UNSPECIFIED": self = .profileUnspecified
      case "OPTIMIZE_UTILIZATION": self = .optimizeUtilization
      case "BALANCED": self = .balanced
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .profileUnspecified
      case 1: self = .optimizeUtilization
      case 2: self = .balanced
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .profileUnspecified: return try container.encode(0)
      case .optimizeUtilization: return try container.encode(1)
      case .balanced: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines possible options for Autopilot general profile.
  public enum AutopilotGeneralProfile: Codable, Equatable, Sendable {
    case unspecified
    case noPerformance
    case `none`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .noPerformance: return 1
      case .`none`: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "AUTOPILOT_GENERAL_PROFILE_UNSPECIFIED"
      case .noPerformance: return "NO_PERFORMANCE"
      case .`none`: return "NONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "AUTOPILOT_GENERAL_PROFILE_UNSPECIFIED": self = .unspecified
      case "NO_PERFORMANCE": self = .noPerformance
      case "NONE": self = .`none`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .noPerformance
      case 2: self = .`none`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .noPerformance: return try container.encode(1)
      case .`none`: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.ClusterAutoscaling"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
