// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ClusterUpgradeInfo contains the upgrade information of a cluster.
public struct ClusterUpgradeInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// minor_target_version indicates the target version for minor upgrade.
  public var minorTargetVersion: Swift.String? = nil

  /// patch_target_version indicates the target version for patch upgrade.
  public var patchTargetVersion: Swift.String? = nil

  /// The auto upgrade status.
  public var autoUpgradeStatus: [ClusterUpgradeInfo.AutoUpgradeStatus] = []

  /// The auto upgrade paused reason.
  public var pausedReason: [ClusterUpgradeInfo.AutoUpgradePausedReason] = []

  /// The list of past auto upgrades.
  public var upgradeDetails: [UpgradeDetails] = []

  /// The cluster's current minor version's end of standard support timestamp.
  public var endOfStandardSupportTimestamp: Swift.String? = nil

  /// The cluster's current minor version's end of extended support timestamp.
  public var endOfExtendedSupportTimestamp: Swift.String? = nil

  /// Initialize a new instance of `ClusterUpgradeInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClusterUpgradeInfo().with { $0.minorTargetVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// AutoUpgradeStatus indicates the status of auto upgrade.
  public enum AutoUpgradeStatus: Codable, Equatable, Sendable {
    case unknown
    case active
    case minorUpgradePaused
    case upgradePaused
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .active: return 1
      case .minorUpgradePaused: return 4
      case .upgradePaused: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .active: return "ACTIVE"
      case .minorUpgradePaused: return "MINOR_UPGRADE_PAUSED"
      case .upgradePaused: return "UPGRADE_PAUSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "ACTIVE": self = .active
      case "MINOR_UPGRADE_PAUSED": self = .minorUpgradePaused
      case "UPGRADE_PAUSED": self = .upgradePaused
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .active
      case 4: self = .minorUpgradePaused
      case 5: self = .upgradePaused
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .active: return try container.encode(1)
      case .minorUpgradePaused: return try container.encode(4)
      case .upgradePaused: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// AutoUpgradePausedReason indicates the reason for auto upgrade paused
  /// status.
  public enum AutoUpgradePausedReason: Codable, Equatable, Sendable {
    case unspecified
    case maintenanceWindow
    case clusterDisruptionBudget
    case maintenanceExclusionNoUpgrades
    case maintenanceExclusionNoMinorUpgrades
    case clusterDisruptionBudgetMinorUpgrade
    case systemConfig
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .maintenanceWindow: return 1
      case .clusterDisruptionBudget: return 4
      case .maintenanceExclusionNoUpgrades: return 5
      case .maintenanceExclusionNoMinorUpgrades: return 6
      case .clusterDisruptionBudgetMinorUpgrade: return 7
      case .systemConfig: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "AUTO_UPGRADE_PAUSED_REASON_UNSPECIFIED"
      case .maintenanceWindow: return "MAINTENANCE_WINDOW"
      case .clusterDisruptionBudget: return "CLUSTER_DISRUPTION_BUDGET"
      case .maintenanceExclusionNoUpgrades: return "MAINTENANCE_EXCLUSION_NO_UPGRADES"
      case .maintenanceExclusionNoMinorUpgrades: return "MAINTENANCE_EXCLUSION_NO_MINOR_UPGRADES"
      case .clusterDisruptionBudgetMinorUpgrade: return "CLUSTER_DISRUPTION_BUDGET_MINOR_UPGRADE"
      case .systemConfig: return "SYSTEM_CONFIG"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "AUTO_UPGRADE_PAUSED_REASON_UNSPECIFIED": self = .unspecified
      case "MAINTENANCE_WINDOW": self = .maintenanceWindow
      case "MAINTENANCE_EXCLUSION_NO_UPGRADES": self = .maintenanceExclusionNoUpgrades
      case "MAINTENANCE_EXCLUSION_NO_MINOR_UPGRADES": self = .maintenanceExclusionNoMinorUpgrades
      case "CLUSTER_DISRUPTION_BUDGET": self = .clusterDisruptionBudget
      case "CLUSTER_DISRUPTION_BUDGET_MINOR_UPGRADE": self = .clusterDisruptionBudgetMinorUpgrade
      case "SYSTEM_CONFIG": self = .systemConfig
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .maintenanceWindow
      case 5: self = .maintenanceExclusionNoUpgrades
      case 6: self = .maintenanceExclusionNoMinorUpgrades
      case 4: self = .clusterDisruptionBudget
      case 7: self = .clusterDisruptionBudgetMinorUpgrade
      case 8: self = .systemConfig
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .maintenanceWindow: return try container.encode(1)
      case .clusterDisruptionBudget: return try container.encode(4)
      case .maintenanceExclusionNoUpgrades: return try container.encode(5)
      case .maintenanceExclusionNoMinorUpgrades: return try container.encode(6)
      case .clusterDisruptionBudgetMinorUpgrade: return try container.encode(7)
      case .systemConfig: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.ClusterUpgradeInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
