// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DisruptionBudget defines the upgrade disruption budget for the cluster
/// control plane.
public struct DisruptionBudget: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The minimum duration between two minor version upgrades of the
  /// control plane.
  public var minorVersionDisruptionInterval: GoogleCloudWkt.Duration? = nil

  /// Optional. The minimum duration between two patch version upgrades of the
  /// control plane.
  public var patchVersionDisruptionInterval: GoogleCloudWkt.Duration? = nil

  /// Output only. The last time a minor version upgrade was performed on the
  /// control plane.
  public var lastMinorVersionDisruptionTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last time a disruption was performed on the control plane.
  public var lastDisruptionTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `DisruptionBudget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DisruptionBudget().with { $0.minorVersionDisruptionInterval = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.DisruptionBudget"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
