// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents the Maintenance exclusion option.
public struct MaintenanceExclusionOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Scope specifies the upgrade scope which upgrades are blocked by the
  /// exclusion.
  public var scope: MaintenanceExclusionOptions.Scope = MaintenanceExclusionOptions.Scope()

  /// EndTimeBehavior specifies the behavior of the exclusion end time.
  public var endTimeBehavior: MaintenanceExclusionOptions.EndTimeBehavior =
    MaintenanceExclusionOptions.EndTimeBehavior()

  /// Initialize a new instance of `MaintenanceExclusionOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaintenanceExclusionOptions().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Scope of exclusion.
  public enum Scope: Codable, Equatable, Sendable {
    /// NO_UPGRADES excludes all upgrades, including patch upgrades and minor
    /// upgrades across control planes and nodes. This is the default exclusion
    /// behavior.
    case noUpgrades
    /// NO_MINOR_UPGRADES excludes all minor upgrades for the cluster, only
    /// patches are allowed.
    case noMinorUpgrades
    /// NO_MINOR_OR_NODE_UPGRADES excludes all minor upgrades for the cluster,
    /// and also exclude all node pool upgrades. Only control
    /// plane patches are allowed.
    case noMinorOrNodeUpgrades
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .noUpgrades
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .noUpgrades: return 0
      case .noMinorUpgrades: return 1
      case .noMinorOrNodeUpgrades: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .noUpgrades: return "NO_UPGRADES"
      case .noMinorUpgrades: return "NO_MINOR_UPGRADES"
      case .noMinorOrNodeUpgrades: return "NO_MINOR_OR_NODE_UPGRADES"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Scope/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NO_UPGRADES": self = .noUpgrades
      case "NO_MINOR_UPGRADES": self = .noMinorUpgrades
      case "NO_MINOR_OR_NODE_UPGRADES": self = .noMinorOrNodeUpgrades
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Scope/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .noUpgrades
      case 1: self = .noMinorUpgrades
      case 2: self = .noMinorOrNodeUpgrades
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .noUpgrades: return try container.encode(0)
      case .noMinorUpgrades: return try container.encode(1)
      case .noMinorOrNodeUpgrades: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// EndTimeBehavior specifies the behavior of the exclusion end time.
  public enum EndTimeBehavior: Codable, Equatable, Sendable {
    /// END_TIME_BEHAVIOR_UNSPECIFIED is the default behavior, which is fixed
    /// end time.
    case unspecified
    /// UNTIL_END_OF_SUPPORT means the exclusion will be in effect until the end
    /// of the support of the cluster's current version.
    case untilEndOfSupport
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .untilEndOfSupport: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "END_TIME_BEHAVIOR_UNSPECIFIED"
      case .untilEndOfSupport: return "UNTIL_END_OF_SUPPORT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EndTimeBehavior/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "END_TIME_BEHAVIOR_UNSPECIFIED": self = .unspecified
      case "UNTIL_END_OF_SUPPORT": self = .untilEndOfSupport
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EndTimeBehavior/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .untilEndOfSupport
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .untilEndOfSupport: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.MaintenanceExclusionOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
