// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// MonitoringComponentConfig is cluster monitoring component configuration.
public struct MonitoringComponentConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Select components to collect metrics. An empty set would disable all
  /// monitoring.
  public var enableComponents: [MonitoringComponentConfig.Component] = []

  /// Initialize a new instance of `MonitoringComponentConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MonitoringComponentConfig().with { $0.enableComponents = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// GKE components exposing metrics
  public enum Component: Codable, Equatable, Sendable {
    case unspecified
    case systemComponents
    case apiserver
    case scheduler
    case controllerManager
    case storage
    case hpa
    case pod
    case daemonset
    case deployment
    case statefulset
    case cadvisor
    case kubelet
    case dcgm
    case jobset
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .systemComponents: return 1
      case .apiserver: return 3
      case .scheduler: return 4
      case .controllerManager: return 5
      case .storage: return 7
      case .hpa: return 8
      case .pod: return 9
      case .daemonset: return 10
      case .deployment: return 11
      case .statefulset: return 12
      case .cadvisor: return 13
      case .kubelet: return 14
      case .dcgm: return 15
      case .jobset: return 16
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "COMPONENT_UNSPECIFIED"
      case .systemComponents: return "SYSTEM_COMPONENTS"
      case .apiserver: return "APISERVER"
      case .scheduler: return "SCHEDULER"
      case .controllerManager: return "CONTROLLER_MANAGER"
      case .storage: return "STORAGE"
      case .hpa: return "HPA"
      case .pod: return "POD"
      case .daemonset: return "DAEMONSET"
      case .deployment: return "DEPLOYMENT"
      case .statefulset: return "STATEFULSET"
      case .cadvisor: return "CADVISOR"
      case .kubelet: return "KUBELET"
      case .dcgm: return "DCGM"
      case .jobset: return "JOBSET"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "COMPONENT_UNSPECIFIED": self = .unspecified
      case "SYSTEM_COMPONENTS": self = .systemComponents
      case "APISERVER": self = .apiserver
      case "SCHEDULER": self = .scheduler
      case "CONTROLLER_MANAGER": self = .controllerManager
      case "STORAGE": self = .storage
      case "HPA": self = .hpa
      case "POD": self = .pod
      case "DAEMONSET": self = .daemonset
      case "DEPLOYMENT": self = .deployment
      case "STATEFULSET": self = .statefulset
      case "CADVISOR": self = .cadvisor
      case "KUBELET": self = .kubelet
      case "DCGM": self = .dcgm
      case "JOBSET": self = .jobset
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .systemComponents
      case 3: self = .apiserver
      case 4: self = .scheduler
      case 5: self = .controllerManager
      case 7: self = .storage
      case 8: self = .hpa
      case 9: self = .pod
      case 10: self = .daemonset
      case 11: self = .deployment
      case 12: self = .statefulset
      case 13: self = .cadvisor
      case 14: self = .kubelet
      case 15: self = .dcgm
      case 16: self = .jobset
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .systemComponents: return try container.encode(1)
      case .apiserver: return try container.encode(3)
      case .scheduler: return try container.encode(4)
      case .controllerManager: return try container.encode(5)
      case .storage: return try container.encode(7)
      case .hpa: return try container.encode(8)
      case .pod: return try container.encode(9)
      case .daemonset: return try container.encode(10)
      case .deployment: return try container.encode(11)
      case .statefulset: return try container.encode(12)
      case .cadvisor: return try container.encode(13)
      case .kubelet: return try container.encode(14)
      case .dcgm: return try container.encode(15)
      case .jobset: return try container.encode(16)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.MonitoringComponentConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
