// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// NodePool contains the name and configuration for a cluster's node pool.
/// Node pools are a set of nodes (i.e. VM's), with a common configuration and
/// specification, under the control of the cluster master. They may have a set
/// of Kubernetes labels applied to them, which may be used to reference them
/// during pod scheduling. They may also be resized up or down, to accommodate
/// the workload.
public struct NodePool: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the node pool.
  public var name: Swift.String

  /// The node configuration of the pool.
  public var config: NodeConfig?

  /// The initial node count for the pool. You must ensure that your
  /// Compute Engine [resource
  /// quota](https://cloud.google.com/compute/quotas)
  /// is sufficient for this number of instances. You must also have available
  /// firewall and routes quota.
  public var initialNodeCount: Swift.Int32

  /// The list of Google Compute Engine
  /// [zones](https://cloud.google.com/compute/docs/zones#available)
  /// in which the NodePool's nodes should be located.
  ///
  /// If this value is unspecified during node pool creation, the
  /// [Cluster.Locations](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.FIELDS.locations)
  /// value will be used, instead.
  ///
  /// Warning: changing node pool locations will result in nodes being added
  /// and/or removed.
  public var locations: [Swift.String]

  /// Networking configuration for this NodePool. If specified, it overrides the
  /// cluster-level defaults.
  public var networkConfig: NodeNetworkConfig?

  /// Output only. Server-defined URL for the resource.
  public var selfLink: Swift.String

  /// The version of Kubernetes running on this NodePool's nodes. If unspecified,
  /// it defaults as described
  /// [here](https://cloud.google.com/kubernetes-engine/versioning#specifying_node_version).
  public var version: Swift.String

  /// Output only. The resource URLs of the [managed instance
  /// groups](https://cloud.google.com/compute/docs/instance-groups/creating-groups-of-managed-instances)
  /// associated with this node pool.
  /// During the node pool blue-green upgrade operation, the URLs contain both
  /// blue and green resources.
  public var instanceGroupUrls: [Swift.String]

  /// Output only. The status of the nodes in this pool instance.
  public var status: NodePool.Status

  /// Output only. Deprecated. Use conditions instead.
  /// Additional information about the current status of this
  /// node pool instance, if available.
  public var statusMessage: Swift.String

  /// Autoscaler configuration for this NodePool. Autoscaler is enabled
  /// only if a valid configuration is present.
  public var autoscaling: NodePoolAutoscaling?

  /// NodeManagement configuration for this NodePool.
  public var management: NodeManagement?

  /// The constraint on the maximum number of pods that can be run
  /// simultaneously on a node in the node pool.
  public var maxPodsConstraint: MaxPodsConstraint?

  /// Which conditions caused the current node pool state.
  public var conditions: [StatusCondition]

  /// Output only. The pod CIDR block size per node in this node pool.
  public var podIpv4CidrSize: Swift.Int32

  /// Upgrade settings control disruption and speed of the upgrade.
  public var upgradeSettings: NodePool.UpgradeSettings?

  /// Specifies the node placement policy.
  public var placementPolicy: NodePool.PlacementPolicy?

  /// Output only. Update info contains relevant information during a node
  /// pool update.
  public var updateInfo: NodePool.UpdateInfo?

  /// This checksum is computed by the server based on the value of node pool
  /// fields, and may be sent on update requests to ensure the client has an
  /// up-to-date value before proceeding.
  public var etag: Swift.String

  /// Specifies the configuration of queued provisioning.
  public var queuedProvisioning: NodePool.QueuedProvisioning?

  /// Enable best effort provisioning for nodes
  public var bestEffortProvisioning: BestEffortProvisioning?

  /// Specifies the node drain configuration for this node pool.
  public var nodeDrainConfig: NodePool.NodeDrainConfig?

  /// Optional. Specifies the maintenance policy for the node pool.
  public var maintenancePolicy: NodePool.NodePoolMaintenancePolicy?

  /// Initialize a new instance of `NodePool`.
  public init(
    name: Swift.String = Swift.String(),
    config: NodeConfig? = nil,
    initialNodeCount: Swift.Int32 = Swift.Int32(),
    locations: [Swift.String] = [],
    networkConfig: NodeNetworkConfig? = nil,
    selfLink: Swift.String = Swift.String(),
    version: Swift.String = Swift.String(),
    instanceGroupUrls: [Swift.String] = [],
    status: NodePool.Status = NodePool.Status(),
    statusMessage: Swift.String = Swift.String(),
    autoscaling: NodePoolAutoscaling? = nil,
    management: NodeManagement? = nil,
    maxPodsConstraint: MaxPodsConstraint? = nil,
    conditions: [StatusCondition] = [],
    podIpv4CidrSize: Swift.Int32 = Swift.Int32(),
    upgradeSettings: NodePool.UpgradeSettings? = nil,
    placementPolicy: NodePool.PlacementPolicy? = nil,
    updateInfo: NodePool.UpdateInfo? = nil,
    etag: Swift.String = Swift.String(),
    queuedProvisioning: NodePool.QueuedProvisioning? = nil,
    bestEffortProvisioning: BestEffortProvisioning? = nil,
    nodeDrainConfig: NodePool.NodeDrainConfig? = nil,
    maintenancePolicy: NodePool.NodePoolMaintenancePolicy? = nil,
  ) {
    self.name = name
    self.config = config
    self.initialNodeCount = initialNodeCount
    self.locations = locations
    self.networkConfig = networkConfig
    self.selfLink = selfLink
    self.version = version
    self.instanceGroupUrls = instanceGroupUrls
    self.status = status
    self.statusMessage = statusMessage
    self.autoscaling = autoscaling
    self.management = management
    self.maxPodsConstraint = maxPodsConstraint
    self.conditions = conditions
    self.podIpv4CidrSize = podIpv4CidrSize
    self.upgradeSettings = upgradeSettings
    self.placementPolicy = placementPolicy
    self.updateInfo = updateInfo
    self.etag = etag
    self.queuedProvisioning = queuedProvisioning
    self.bestEffortProvisioning = bestEffortProvisioning
    self.nodeDrainConfig = nodeDrainConfig
    self.maintenancePolicy = maintenancePolicy
  }

  /// These upgrade settings control the level of parallelism and the level of
  /// disruption caused by an upgrade.
  ///
  /// maxUnavailable controls the number of nodes that can be simultaneously
  /// unavailable.
  ///
  /// maxSurge controls the number of additional nodes that can be added to the
  /// node pool temporarily for the time of the upgrade to increase the number of
  /// available nodes.
  ///
  /// (maxUnavailable + maxSurge) determines the level of parallelism (how many
  /// nodes are being upgraded at the same time).
  ///
  /// Note: upgrades inevitably introduce some disruption since workloads need to
  /// be moved from old nodes to new, upgraded ones. Even if maxUnavailable=0,
  /// this holds true. (Disruption stays within the limits of
  /// PodDisruptionBudget, if it is configured.)
  ///
  /// Consider a hypothetical node pool with 5 nodes having maxSurge=2,
  /// maxUnavailable=1. This means the upgrade process upgrades 3 nodes
  /// simultaneously. It creates 2 additional (upgraded) nodes, then it brings
  /// down 3 old (not yet upgraded) nodes at the same time. This ensures that
  /// there are always at least 4 nodes available.
  ///
  /// These upgrade settings configure the upgrade strategy for the node pool.
  /// Use strategy to switch between the strategies applied to the node pool.
  ///
  /// If the strategy is ROLLING, use max_surge and max_unavailable to control
  /// the level of parallelism and the level of disruption caused by upgrade.
  /// 1. maxSurge controls the number of additional nodes that can be added to
  /// the node pool temporarily for the time of the upgrade to increase the
  /// number of available nodes.
  /// 2. maxUnavailable controls the number of nodes that can be simultaneously
  /// unavailable.
  /// 3. (maxUnavailable + maxSurge) determines the level of parallelism (how
  /// many nodes are being upgraded at the same time).
  ///
  /// If the strategy is BLUE_GREEN, use blue_green_settings to configure the
  /// blue-green upgrade related settings.
  /// 1. standard_rollout_policy is the default policy. The policy is used to
  /// control the way blue pool gets drained. The draining is executed in the
  /// batch mode. The batch size could be specified as either percentage of the
  /// node pool size or the number of nodes. batch_soak_duration is the soak
  /// time after each batch gets drained.
  /// 2. node_pool_soak_duration is the soak time after all blue nodes are
  /// drained. After this period, the blue pool nodes will be deleted.
  public struct UpgradeSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The maximum number of nodes that can be created beyond the current size
    /// of the node pool during the upgrade process.
    public var maxSurge: Swift.Int32

    /// The maximum number of nodes that can be simultaneously unavailable during
    /// the upgrade process. A node is considered available if its status is
    /// Ready.
    public var maxUnavailable: Swift.Int32

    /// Update strategy of the node pool.
    public var strategy: NodePoolUpdateStrategy?

    /// Settings for blue-green upgrade strategy.
    public var blueGreenSettings: BlueGreenSettings?

    /// Initialize a new instance of `UpgradeSettings`.
    public init(
      maxSurge: Swift.Int32 = Swift.Int32(),
      maxUnavailable: Swift.Int32 = Swift.Int32(),
      strategy: NodePoolUpdateStrategy? = nil,
      blueGreenSettings: BlueGreenSettings? = nil,
    ) {
      self.maxSurge = maxSurge
      self.maxUnavailable = maxUnavailable
      self.strategy = strategy
      self.blueGreenSettings = blueGreenSettings
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.NodePool.UpgradeSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// UpdateInfo contains resource (instance groups, etc), status and other
  /// intermediate information relevant to a node pool upgrade.
  public struct UpdateInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Information of a blue-green upgrade.
    public var blueGreenInfo: NodePool.UpdateInfo.BlueGreenInfo?

    /// Initialize a new instance of `UpdateInfo`.
    public init(
      blueGreenInfo: NodePool.UpdateInfo.BlueGreenInfo? = nil,
    ) {
      self.blueGreenInfo = blueGreenInfo
    }

    /// Information relevant to blue-green upgrade.
    public struct BlueGreenInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Current blue-green upgrade phase.
      public var phase: NodePool.UpdateInfo.BlueGreenInfo.Phase

      /// The resource URLs of the [managed instance groups]
      /// (/compute/docs/instance-groups/creating-groups-of-managed-instances)
      /// associated with blue pool.
      public var blueInstanceGroupUrls: [Swift.String]

      /// The resource URLs of the [managed instance groups]
      /// (/compute/docs/instance-groups/creating-groups-of-managed-instances)
      /// associated with green pool.
      public var greenInstanceGroupUrls: [Swift.String]

      /// Time to start deleting blue pool to complete blue-green upgrade,
      /// in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
      public var bluePoolDeletionStartTime: Swift.String

      /// Version of green pool.
      public var greenPoolVersion: Swift.String

      /// Initialize a new instance of `BlueGreenInfo`.
      public init(
        phase: NodePool.UpdateInfo.BlueGreenInfo.Phase = NodePool.UpdateInfo.BlueGreenInfo.Phase(),
        blueInstanceGroupUrls: [Swift.String] = [],
        greenInstanceGroupUrls: [Swift.String] = [],
        bluePoolDeletionStartTime: Swift.String = Swift.String(),
        greenPoolVersion: Swift.String = Swift.String(),
      ) {
        self.phase = phase
        self.blueInstanceGroupUrls = blueInstanceGroupUrls
        self.greenInstanceGroupUrls = greenInstanceGroupUrls
        self.bluePoolDeletionStartTime = bluePoolDeletionStartTime
        self.greenPoolVersion = greenPoolVersion
      }

      /// Phase represents the different stages blue-green upgrade is running in.
      public enum Phase: Codable, Equatable, Sendable {
        case unspecified
        case updateStarted
        case creatingGreenPool
        case cordoningBluePool
        case drainingBluePool
        case nodePoolSoaking
        case deletingBluePool
        case rollbackStarted
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .updateStarted: return 1
          case .creatingGreenPool: return 2
          case .cordoningBluePool: return 3
          case .drainingBluePool: return 4
          case .nodePoolSoaking: return 5
          case .deletingBluePool: return 6
          case .rollbackStarted: return 7
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: String? {
          switch self {
          case .unspecified: return "PHASE_UNSPECIFIED"
          case .updateStarted: return "UPDATE_STARTED"
          case .creatingGreenPool: return "CREATING_GREEN_POOL"
          case .cordoningBluePool: return "CORDONING_BLUE_POOL"
          case .drainingBluePool: return "DRAINING_BLUE_POOL"
          case .nodePoolSoaking: return "NODE_POOL_SOAKING"
          case .deletingBluePool: return "DELETING_BLUE_POOL"
          case .rollbackStarted: return "ROLLBACK_STARTED"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
        public init(stringValue: String) {
          switch stringValue {
          case "PHASE_UNSPECIFIED": self = .unspecified
          case "UPDATE_STARTED": self = .updateStarted
          case "CREATING_GREEN_POOL": self = .creatingGreenPool
          case "CORDONING_BLUE_POOL": self = .cordoningBluePool
          case "DRAINING_BLUE_POOL": self = .drainingBluePool
          case "NODE_POOL_SOAKING": self = .nodePoolSoaking
          case "DELETING_BLUE_POOL": self = .deletingBluePool
          case "ROLLBACK_STARTED": self = .rollbackStarted
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .updateStarted
          case 2: self = .creatingGreenPool
          case 3: self = .cordoningBluePool
          case 4: self = .drainingBluePool
          case 5: self = .nodePoolSoaking
          case 6: self = .deletingBluePool
          case 7: self = .rollbackStarted
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .updateStarted: return try container.encode(1)
          case .creatingGreenPool: return try container.encode(2)
          case .cordoningBluePool: return try container.encode(3)
          case .drainingBluePool: return try container.encode(4)
          case .nodePoolSoaking: return try container.encode(5)
          case .deletingBluePool: return try container.encode(6)
          case .rollbackStarted: return try container.encode(7)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.container.v1.NodePool.UpdateInfo.BlueGreenInfo"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.NodePool.UpdateInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// PlacementPolicy defines the placement policy used by the node pool.
  public struct PlacementPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The type of placement.
    public var type: NodePool.PlacementPolicy.Type_

    /// Optional. TPU placement topology for pod slice node pool.
    /// https://cloud.google.com/tpu/docs/types-topologies#tpu_topologies
    public var tpuTopology: Swift.String

    /// If set, refers to the name of a custom resource policy supplied by the
    /// user. The resource policy must be in the same project and region as the
    /// node pool. If not found, InvalidArgument error is returned.
    public var policyName: Swift.String

    /// Initialize a new instance of `PlacementPolicy`.
    public init(
      type: NodePool.PlacementPolicy.Type_ = NodePool.PlacementPolicy.Type_(),
      tpuTopology: Swift.String = Swift.String(),
      policyName: Swift.String = Swift.String(),
    ) {
      self.type = type
      self.tpuTopology = tpuTopology
      self.policyName = policyName
    }

    /// Type defines the type of placement policy.
    public enum Type_: Codable, Equatable, Sendable {
      case unspecified
      case compact
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .compact: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .compact: return "COMPACT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "COMPACT": self = .compact
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .compact
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .compact: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.NodePool.PlacementPolicy"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// QueuedProvisioning defines the queued provisioning used by the node pool.
  public struct QueuedProvisioning: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Denotes that this node pool is QRM specific, meaning nodes can be only
    /// obtained through queuing via the Cluster Autoscaler ProvisioningRequest
    /// API.
    public var enabled: Swift.Bool

    /// Initialize a new instance of `QueuedProvisioning`.
    public init(
      enabled: Swift.Bool = Swift.Bool(),
    ) {
      self.enabled = enabled
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.NodePool.QueuedProvisioning"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// NodeDrainConfig contains the node drain related configurations for this
  /// node pool.
  public struct NodeDrainConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The duration of the PDB timeout period for node drain.
    public var pdbTimeoutDuration: GoogleCloudWkt.Duration?

    /// The duration of the grace termination period for node drain.
    public var graceTerminationDuration: GoogleCloudWkt.Duration?

    /// Whether to respect PDB during node pool deletion.
    public var respectPdbDuringNodePoolDeletion: Swift.Bool?

    /// Initialize a new instance of `NodeDrainConfig`.
    public init(
      pdbTimeoutDuration: GoogleCloudWkt.Duration? = nil,
      graceTerminationDuration: GoogleCloudWkt.Duration? = nil,
      respectPdbDuringNodePoolDeletion: Swift.Bool? = nil,
    ) {
      self.pdbTimeoutDuration = pdbTimeoutDuration
      self.graceTerminationDuration = graceTerminationDuration
      self.respectPdbDuringNodePoolDeletion = respectPdbDuringNodePoolDeletion
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.NodePool.NodeDrainConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the maintenance exclusion for the node pool.
  public struct ExclusionUntilEndOfSupport: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Indicates whether the exclusion is enabled.
    public var enabled: Swift.Bool

    /// Output only. The start time of the maintenance exclusion. It is output
    /// only. It is the exclusion creation time.
    public var startTime: GoogleCloudWkt.Timestamp?

    /// Output only. The end time of the maintenance exclusion. It is output
    /// only. It is the cluster control plane version's end of support time, or
    /// end of extended support time when the cluster is on extended support
    /// channel.
    public var endTime: GoogleCloudWkt.Timestamp?

    /// Initialize a new instance of `ExclusionUntilEndOfSupport`.
    public init(
      enabled: Swift.Bool = Swift.Bool(),
      startTime: GoogleCloudWkt.Timestamp? = nil,
      endTime: GoogleCloudWkt.Timestamp? = nil,
    ) {
      self.enabled = enabled
      self.startTime = startTime
      self.endTime = endTime
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.NodePool.ExclusionUntilEndOfSupport"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the maintenance policy for the node pool.
  public struct NodePoolMaintenancePolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The exclusion until end of support for the node pool.
    public var exclusionUntilEndOfSupport: NodePool.ExclusionUntilEndOfSupport?

    /// Initialize a new instance of `NodePoolMaintenancePolicy`.
    public init(
      exclusionUntilEndOfSupport: NodePool.ExclusionUntilEndOfSupport? = nil,
    ) {
      self.exclusionUntilEndOfSupport = exclusionUntilEndOfSupport
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.NodePool.NodePoolMaintenancePolicy"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The current status of the node pool instance.
  public enum Status: Codable, Equatable, Sendable {
    case unspecified
    case provisioning
    case running
    case runningWithError
    case reconciling
    case stopping
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .running: return 2
      case .runningWithError: return 3
      case .reconciling: return 4
      case .stopping: return 5
      case .error: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .running: return "RUNNING"
      case .runningWithError: return "RUNNING_WITH_ERROR"
      case .reconciling: return "RECONCILING"
      case .stopping: return "STOPPING"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "RUNNING": self = .running
      case "RUNNING_WITH_ERROR": self = .runningWithError
      case "RECONCILING": self = .reconciling
      case "STOPPING": self = .stopping
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .running
      case 3: self = .runningWithError
      case 4: self = .reconciling
      case 5: self = .stopping
      case 6: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .provisioning: return try container.encode(1)
      case .running: return try container.encode(2)
      case .runningWithError: return try container.encode(3)
      case .reconciling: return try container.encode(4)
      case .stopping: return try container.encode(5)
      case .error: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.NodePool"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
