// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// NodePoolAutoscaling contains information required by cluster autoscaler to
/// adjust the size of the node pool to the current cluster usage.
public struct NodePoolAutoscaling: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Is autoscaling enabled for this node pool.
  public var enabled: Swift.Bool

  /// Minimum number of nodes for one location in the node pool. Must be greater
  /// than or equal to 0 and less than or equal to max_node_count.
  public var minNodeCount: Swift.Int32

  /// Maximum number of nodes for one location in the node pool. Must be >=
  /// min_node_count. There has to be enough quota to scale up the cluster.
  public var maxNodeCount: Swift.Int32

  /// Can this node pool be deleted automatically.
  public var autoprovisioned: Swift.Bool

  /// Location policy used when scaling up a nodepool.
  public var locationPolicy: NodePoolAutoscaling.LocationPolicy

  /// Minimum number of nodes in the node pool. Must be greater than or equal
  /// to 0 and less than or equal to total_max_node_count.
  /// The total_*_node_count fields are mutually exclusive with the *_node_count
  /// fields.
  public var totalMinNodeCount: Swift.Int32

  /// Maximum number of nodes in the node pool. Must be greater than or equal to
  /// total_min_node_count. There has to be enough quota to scale up the cluster.
  /// The total_*_node_count fields are mutually exclusive with the *_node_count
  /// fields.
  public var totalMaxNodeCount: Swift.Int32

  /// Initialize a new instance of `NodePoolAutoscaling`.
  public init(
    enabled: Swift.Bool = Swift.Bool(),
    minNodeCount: Swift.Int32 = Swift.Int32(),
    maxNodeCount: Swift.Int32 = Swift.Int32(),
    autoprovisioned: Swift.Bool = Swift.Bool(),
    locationPolicy: NodePoolAutoscaling.LocationPolicy = NodePoolAutoscaling.LocationPolicy(),
    totalMinNodeCount: Swift.Int32 = Swift.Int32(),
    totalMaxNodeCount: Swift.Int32 = Swift.Int32(),
  ) {
    self.enabled = enabled
    self.minNodeCount = minNodeCount
    self.maxNodeCount = maxNodeCount
    self.autoprovisioned = autoprovisioned
    self.locationPolicy = locationPolicy
    self.totalMinNodeCount = totalMinNodeCount
    self.totalMaxNodeCount = totalMaxNodeCount
  }

  /// Location policy specifies how zones are picked when scaling up the
  /// nodepool.
  public enum LocationPolicy: Codable, Equatable, Sendable {
    case unspecified
    case balanced
    case any
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .balanced: return 1
      case .any: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "LOCATION_POLICY_UNSPECIFIED"
      case .balanced: return "BALANCED"
      case .any: return "ANY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "LOCATION_POLICY_UNSPECIFIED": self = .unspecified
      case "BALANCED": self = .balanced
      case "ANY": self = .any
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .balanced
      case 2: self = .any
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .balanced: return try container.encode(1)
      case .any: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.NodePoolAutoscaling"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
