// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Node pool configs that apply to all auto-provisioned node pools
/// in autopilot clusters and node auto-provisioning enabled clusters.
public struct NodePoolAutoConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The list of instance tags applied to all nodes. Tags are used to identify
  /// valid sources or targets for network firewalls and are specified by
  /// the client during cluster creation. Each tag within the list
  /// must comply with RFC1035.
  public var networkTags: NetworkTags?

  /// Resource manager tag keys and values to be attached to the nodes
  /// for managing Compute Engine firewalls using Network Firewall Policies.
  public var resourceManagerTags: ResourceManagerTags?

  /// NodeKubeletConfig controls the defaults for autoprovisioned node-pools.
  ///
  /// Currently only `insecure_kubelet_readonly_port_enabled` can be set here.
  public var nodeKubeletConfig: NodeKubeletConfig?

  /// Output only. Configuration options for Linux nodes.
  public var linuxNodeConfig: LinuxNodeConfig?

  /// Initialize a new instance of `NodePoolAutoConfig`.
  public init(
    networkTags: NetworkTags? = nil,
    resourceManagerTags: ResourceManagerTags? = nil,
    nodeKubeletConfig: NodeKubeletConfig? = nil,
    linuxNodeConfig: LinuxNodeConfig? = nil,
  ) {
    self.networkTags = networkTags
    self.resourceManagerTags = resourceManagerTags
    self.nodeKubeletConfig = nodeKubeletConfig
    self.linuxNodeConfig = linuxNodeConfig
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.NodePoolAutoConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
