// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration options for the Ray Operator add-on.
public struct RayOperatorConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Whether the Ray Operator addon is enabled for this cluster.
  public var enabled: Swift.Bool

  /// Optional. Logging configuration for Ray clusters.
  public var rayClusterLoggingConfig: RayClusterLoggingConfig?

  /// Optional. Monitoring configuration for Ray clusters.
  public var rayClusterMonitoringConfig: RayClusterMonitoringConfig?

  /// Initialize a new instance of `RayOperatorConfig`.
  public init(
    enabled: Swift.Bool = Swift.Bool(),
    rayClusterLoggingConfig: RayClusterLoggingConfig? = nil,
    rayClusterMonitoringConfig: RayClusterMonitoringConfig? = nil,
  ) {
    self.enabled = enabled
    self.rayClusterLoggingConfig = rayClusterLoggingConfig
    self.rayClusterMonitoringConfig = rayClusterMonitoringConfig
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.RayOperatorConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
