// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Kubernetes Engine service configuration.
public struct ServerConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Version of Kubernetes the service deploys by default.
  public var defaultClusterVersion: Swift.String

  /// List of valid node upgrade target versions, in descending order.
  public var validNodeVersions: [Swift.String]

  /// Default image type.
  public var defaultImageType: Swift.String

  /// List of valid image types.
  public var validImageTypes: [Swift.String]

  /// List of valid master versions, in descending order.
  public var validMasterVersions: [Swift.String]

  /// List of release channel configurations.
  public var channels: [ServerConfig.ReleaseChannelConfig]

  /// Initialize a new instance of `ServerConfig`.
  public init(
    defaultClusterVersion: Swift.String = Swift.String(),
    validNodeVersions: [Swift.String] = [],
    defaultImageType: Swift.String = Swift.String(),
    validImageTypes: [Swift.String] = [],
    validMasterVersions: [Swift.String] = [],
    channels: [ServerConfig.ReleaseChannelConfig] = [],
  ) {
    self.defaultClusterVersion = defaultClusterVersion
    self.validNodeVersions = validNodeVersions
    self.defaultImageType = defaultImageType
    self.validImageTypes = validImageTypes
    self.validMasterVersions = validMasterVersions
    self.channels = channels
  }

  /// ReleaseChannelConfig exposes configuration for a release channel.
  public struct ReleaseChannelConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The release channel this configuration applies to.
    public var channel: ReleaseChannel.Channel

    /// The default version for newly created clusters on the channel.
    public var defaultVersion: Swift.String

    /// List of valid versions for the channel.
    public var validVersions: [Swift.String]

    /// The auto upgrade target version for clusters on the channel.
    public var upgradeTargetVersion: Swift.String

    /// Initialize a new instance of `ReleaseChannelConfig`.
    public init(
      channel: ReleaseChannel.Channel = ReleaseChannel.Channel(),
      defaultVersion: Swift.String = Swift.String(),
      validVersions: [Swift.String] = [],
      upgradeTargetVersion: Swift.String = Swift.String(),
    ) {
      self.channel = channel
      self.defaultVersion = defaultVersion
      self.validVersions = validVersions
      self.upgradeTargetVersion = upgradeTargetVersion
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.container.v1.ServerConfig.ReleaseChannelConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.ServerConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
