// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// SetMasterAuthRequest updates the admin password of a cluster.
public struct SetMasterAuthRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Deprecated. The Google Developers Console [project ID or project
  /// number](https://cloud.google.com/resource-manager/docs/creating-managing-projects).
  /// This field has been deprecated and replaced by the name field.
  @available(*, deprecated)
  public var projectId: Swift.String = Swift.String()

  /// Deprecated. The name of the Google Compute Engine
  /// [zone](https://cloud.google.com/compute/docs/zones#available)
  /// in which the cluster resides. This field has been deprecated and replaced
  /// by the name field.
  @available(*, deprecated)
  public var zone: Swift.String = Swift.String()

  /// Deprecated. The name of the cluster to upgrade.
  /// This field has been deprecated and replaced by the name field.
  @available(*, deprecated)
  public var clusterId: Swift.String = Swift.String()

  /// Required. The exact form of action to be taken on the master auth.
  public var action: SetMasterAuthRequest.Action = SetMasterAuthRequest.Action()

  /// Required. A description of the update.
  public var update: MasterAuth? = nil

  /// The name (project, location, cluster) of the cluster to set auth.
  /// Specified in the format `projects/*/locations/*/clusters/*`.
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `SetMasterAuthRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SetMasterAuthRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Operation type: what type update to perform.
  public enum Action: Codable, Equatable, Sendable {
    /// Operation is unknown and will error out.
    case unknown
    /// Set the password to a user generated value.
    case setPassword
    /// Generate a new password and set it to that.
    case generatePassword
    /// Set the username.  If an empty username is provided, basic authentication
    /// is disabled for the cluster.  If a non-empty username is provided, basic
    /// authentication is enabled, with either a provided password or a generated
    /// one.
    case setUsername
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .setPassword: return 1
      case .generatePassword: return 2
      case .setUsername: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .setPassword: return "SET_PASSWORD"
      case .generatePassword: return "GENERATE_PASSWORD"
      case .setUsername: return "SET_USERNAME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "SET_PASSWORD": self = .setPassword
      case "GENERATE_PASSWORD": self = .generatePassword
      case "SET_USERNAME": self = .setUsername
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .setPassword
      case 2: self = .generatePassword
      case 3: self = .setUsername
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .setPassword: return try container.encode(1)
      case .generatePassword: return try container.encode(2)
      case .setUsername: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.SetMasterAuthRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
