// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// SoleTenantConfig contains the NodeAffinities to specify what shared sole
/// tenant node groups should back the node pool.
public struct SoleTenantConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// NodeAffinities used to match to a shared sole tenant node group.
  public var nodeAffinities: [SoleTenantConfig.NodeAffinity] = []

  /// Optional. The minimum number of virtual CPUs this instance will consume
  /// when running on a sole-tenant node. This field can only be set if the node
  /// pool is created in a shared sole-tenant node group.
  public var minNodeCpus: Swift.Int32? = nil

  /// Initialize a new instance of `SoleTenantConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SoleTenantConfig().with { $0.nodeAffinities = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Specifies the NodeAffinity key, values, and affinity operator according to
  /// [shared sole tenant node group
  /// affinities](https://cloud.google.com/compute/docs/nodes/sole-tenant-nodes#node_affinity_and_anti-affinity).
  public struct NodeAffinity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Key for NodeAffinity.
    public var key: Swift.String = Swift.String()

    /// Operator for NodeAffinity.
    public var `operator`: SoleTenantConfig.NodeAffinity.Operator = SoleTenantConfig.NodeAffinity
      .Operator()

    /// Values for NodeAffinity.
    public var values: [Swift.String] = []

    /// Initialize a new instance of `NodeAffinity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NodeAffinity().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case key = "key"
      case `operator` = "operator"
      case values = "values"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.key = try container.decode(Swift.String.self, forKey: .key)
      self.`operator` = try container.decode(
        SoleTenantConfig.NodeAffinity.Operator.self, forKey: .`operator`)
      self.values = try container.decode([Swift.String].self, forKey: .values)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.key, forKey: .key)
      try container.encode(self.`operator`, forKey: .`operator`)
      try container.encode(self.values, forKey: .values)
    }

    /// Operator allows user to specify affinity or anti-affinity for the
    /// given key values.
    public enum Operator: Codable, Equatable, Sendable {
      /// Invalid or unspecified affinity operator.
      case unspecified
      /// Affinity operator.
      case `in`
      /// Anti-affinity operator.
      case notIn
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .`in`: return 1
        case .notIn: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "OPERATOR_UNSPECIFIED"
        case .`in`: return "IN"
        case .notIn: return "NOT_IN"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "OPERATOR_UNSPECIFIED": self = .unspecified
        case "IN": self = .`in`
        case "NOT_IN": self = .notIn
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .`in`
        case 2: self = .notIn
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .`in`: return try container.encode(1)
        case .notIn: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.container.v1.SoleTenantConfig.NodeAffinity"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.container.v1.SoleTenantConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
