// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// UpgradeAvailableEvent is a notification sent to customers when a new
/// available version is released.
public struct UpgradeAvailableEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The release version available for upgrade.
  public var version: Swift.String

  /// The resource type of the release version.
  public var resourceType: UpgradeResourceType

  /// The release channel of the version. If empty, it means a non-channel
  /// release.
  public var releaseChannel: ReleaseChannel?

  /// Optional relative path to the resource. For example, the relative path of
  /// the node pool.
  public var resource: Swift.String

  /// Initialize a new instance of `UpgradeAvailableEvent`.
  public init(
    version: Swift.String = Swift.String(),
    resourceType: UpgradeResourceType = UpgradeResourceType(),
    releaseChannel: ReleaseChannel? = nil,
    resource: Swift.String = Swift.String(),
  ) {
    self.version = version
    self.resourceType = resourceType
    self.releaseChannel = releaseChannel
    self.resource = resource
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.UpgradeAvailableEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
