// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// UpgradeInfoEvent is a notification sent to customers about the upgrade
/// information of a resource.
public struct UpgradeInfoEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource type associated with the upgrade.
  public var resourceType: UpgradeResourceType

  /// The operation associated with this upgrade.
  public var operation: Swift.String

  /// The time when the operation was started.
  public var startTime: GoogleCloudWkt.Timestamp?

  /// The time when the operation ended.
  public var endTime: GoogleCloudWkt.Timestamp?

  /// The current version before the upgrade.
  public var currentVersion: Swift.String

  /// The target version for the upgrade.
  public var targetVersion: Swift.String

  /// Optional relative path to the resource. For example in node pool upgrades,
  /// the relative path of the node pool.
  public var resource: Swift.String

  /// Output only. The state of the upgrade.
  public var state: UpgradeInfoEvent.State

  /// The end of standard support timestamp.
  public var standardSupportEndTime: GoogleCloudWkt.Timestamp?

  /// The end of extended support timestamp.
  public var extendedSupportEndTime: GoogleCloudWkt.Timestamp?

  /// A brief description of the event.
  public var description: Swift.String

  /// The type of the event.
  public var eventType: UpgradeInfoEvent.EventType

  /// The information about the disruption event. This field is only populated
  /// when event_type is DISRUPTION_EVENT.
  public var disruptionEvent: DisruptionEvent?

  /// Initialize a new instance of `UpgradeInfoEvent`.
  public init(
    resourceType: UpgradeResourceType = UpgradeResourceType(),
    operation: Swift.String = Swift.String(),
    startTime: GoogleCloudWkt.Timestamp? = nil,
    endTime: GoogleCloudWkt.Timestamp? = nil,
    currentVersion: Swift.String = Swift.String(),
    targetVersion: Swift.String = Swift.String(),
    resource: Swift.String = Swift.String(),
    state: UpgradeInfoEvent.State = UpgradeInfoEvent.State(),
    standardSupportEndTime: GoogleCloudWkt.Timestamp? = nil,
    extendedSupportEndTime: GoogleCloudWkt.Timestamp? = nil,
    description: Swift.String = Swift.String(),
    eventType: UpgradeInfoEvent.EventType = UpgradeInfoEvent.EventType(),
    disruptionEvent: DisruptionEvent? = nil,
  ) {
    self.resourceType = resourceType
    self.operation = operation
    self.startTime = startTime
    self.endTime = endTime
    self.currentVersion = currentVersion
    self.targetVersion = targetVersion
    self.resource = resource
    self.state = state
    self.standardSupportEndTime = standardSupportEndTime
    self.extendedSupportEndTime = extendedSupportEndTime
    self.description = description
    self.eventType = eventType
    self.disruptionEvent = disruptionEvent
  }

  /// The state of the upgrade.
  public enum State: Codable, Equatable, Sendable {
    case unspecified
    case scheduled
    case started
    case succeeded
    case failed
    case canceled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scheduled: return 1
      case .started: return 3
      case .succeeded: return 4
      case .failed: return 5
      case .canceled: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .scheduled: return "SCHEDULED"
      case .started: return "STARTED"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .canceled: return "CANCELED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SCHEDULED": self = .scheduled
      case "STARTED": self = .started
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "CANCELED": self = .canceled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scheduled
      case 3: self = .started
      case 4: self = .succeeded
      case 5: self = .failed
      case 6: self = .canceled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .scheduled: return try container.encode(1)
      case .started: return try container.encode(3)
      case .succeeded: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .canceled: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type of the event.
  public enum EventType: Codable, Equatable, Sendable {
    case unspecified
    case endOfSupport
    case cosMilestoneVersionUpdate
    case upgradeLifecycle
    case disruptionEvent
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .endOfSupport: return 1
      case .cosMilestoneVersionUpdate: return 2
      case .upgradeLifecycle: return 3
      case .disruptionEvent: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
      case .endOfSupport: return "END_OF_SUPPORT"
      case .cosMilestoneVersionUpdate: return "COS_MILESTONE_VERSION_UPDATE"
      case .upgradeLifecycle: return "UPGRADE_LIFECYCLE"
      case .disruptionEvent: return "DISRUPTION_EVENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "END_OF_SUPPORT": self = .endOfSupport
      case "COS_MILESTONE_VERSION_UPDATE": self = .cosMilestoneVersionUpdate
      case "UPGRADE_LIFECYCLE": self = .upgradeLifecycle
      case "DISRUPTION_EVENT": self = .disruptionEvent
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .endOfSupport
      case 2: self = .cosMilestoneVersionUpdate
      case 3: self = .upgradeLifecycle
      case 4: self = .disruptionEvent
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .endOfSupport: return try container.encode(1)
      case .cosMilestoneVersionUpdate: return try container.encode(2)
      case .upgradeLifecycle: return try container.encode(3)
      case .disruptionEvent: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.UpgradeInfoEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
