// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// UserManagedKeysConfig holds the resource address to Keys which are used
/// for signing certs and token that are used for communication within cluster.
public struct UserManagedKeysConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The Certificate Authority Service caPool to use for the cluster CA in this
  /// cluster.
  public var clusterCa: Swift.String

  /// Resource path of the Certificate Authority Service caPool to use for the
  /// etcd API CA in this cluster.
  public var etcdApiCa: Swift.String

  /// Resource path of the Certificate Authority Service caPool to use for the
  /// etcd peer CA in this cluster.
  public var etcdPeerCa: Swift.String

  /// The Cloud KMS cryptoKeyVersions to use for signing service account JWTs
  /// issued by this cluster.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion}`
  public var serviceAccountSigningKeys: [Swift.String]

  /// The Cloud KMS cryptoKeyVersions to use for verifying service account JWTs
  /// issued by this cluster.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{cryptoKey}/cryptoKeyVersions/{cryptoKeyVersion}`
  public var serviceAccountVerificationKeys: [Swift.String]

  /// The Certificate Authority Service caPool to use for the aggregation CA in
  /// this cluster.
  public var aggregationCa: Swift.String

  /// The Cloud KMS cryptoKey to use for Confidential Hyperdisk on the control
  /// plane nodes.
  public var controlPlaneDiskEncryptionKey: Swift.String

  /// Output only. All of the versions of the Cloud KMS cryptoKey that are used
  /// by Confidential Hyperdisks on the control plane nodes.
  public var controlPlaneDiskEncryptionKeyVersions: [Swift.String]

  /// Resource path of the Cloud KMS cryptoKey to use for encryption of internal
  /// etcd backups.
  public var gkeopsEtcdBackupEncryptionKey: Swift.String

  /// Initialize a new instance of `UserManagedKeysConfig`.
  public init(
    clusterCa: Swift.String = Swift.String(),
    etcdApiCa: Swift.String = Swift.String(),
    etcdPeerCa: Swift.String = Swift.String(),
    serviceAccountSigningKeys: [Swift.String] = [],
    serviceAccountVerificationKeys: [Swift.String] = [],
    aggregationCa: Swift.String = Swift.String(),
    controlPlaneDiskEncryptionKey: Swift.String = Swift.String(),
    controlPlaneDiskEncryptionKeyVersions: [Swift.String] = [],
    gkeopsEtcdBackupEncryptionKey: Swift.String = Swift.String(),
  ) {
    self.clusterCa = clusterCa
    self.etcdApiCa = etcdApiCa
    self.etcdPeerCa = etcdPeerCa
    self.serviceAccountSigningKeys = serviceAccountSigningKeys
    self.serviceAccountVerificationKeys = serviceAccountVerificationKeys
    self.aggregationCa = aggregationCa
    self.controlPlaneDiskEncryptionKey = controlPlaneDiskEncryptionKey
    self.controlPlaneDiskEncryptionKeyVersions = controlPlaneDiskEncryptionKeyVersions
    self.gkeopsEtcdBackupEncryptionKey = gkeopsEtcdBackupEncryptionKey
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.container.v1.UserManagedKeysConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
